### ISSUE TITLE
3.3.3 -> 4.0.1 upgrade

### ISSUE THREAD

**Issue by robjwilkins** [togglz/togglz#1042]
We have a project which uses Togglz v3.3.3. We upgraded to 4.0.1, but now get exceptions:
`java.lang.IllegalStateException: Could not find the FeatureManager. For web applications please verify that the TogglzFilter starts up correctly. In other deployment scenarios you will typically have to implement a FeatureManagerProvider as described in the 'Advanced Configuration' chapter of the documentation. at org.togglz.core.context.FeatureContext.getFeatureManager(FeatureContext.java:52)`

The only change is the dependency version for togglz libraries.

Unfortunately no automated tests fail because they all use the `TestFeatureManager`, so we only see the problem when actually running the application which is far from ideal.

There are no notes in the 4.0.1 release note which seem to indicate what breaking changes were made in 4.0.1 from 3.x, and there are no upgrade instructions either

**Comment by bennetelli** [comment]
I actually need some more context. How are you running togglz? With Spring Boot?

**Comment by bennetelli** [comment]
It's still on my list to write a blog post about the new release. I will add your case to it as well

**Comment by bennetelli** [comment]
yea, then you will have to upgrade to Spring Boot 3.X.X. There is a breaking change in the way Spring Boot starters work in Spring Boot 2 and 3 and I had to update it.
Using Spring Boot 2 and togglz 4 does not work since togglz 4 is working with the new way Spring Boot starters work.

**Comment by bennetelli** [comment]
Will mark this as closed as it will disappear when you update to SP 3
