### ISSUE TITLE
tests failing in togglz core module in master branch

### ISSUE THREAD

**Issue by devopsd** [togglz/togglz#110]
following tests are failing in Togglz Core:
- `shouldReturnTrueForFeatureOnCorrectMachine(org.togglz.core.activation.IPActivationStrategyTest):
  expected:<true> but was:<false>`
- `multipleMachineIps(org.togglz.core.activation.IPActivationStrategyTest):
  expected:<true> but was:<false>`

**Comment by devopsd** [comment]
Confimed, issues is fixed

**Comment by chkal** [comment]
Thanks for testing :)
