### ISSUE TITLE
Allow togglz to submit csfr token from spring security on action post

### ISSUE THREAD

**Issue by mayn** [togglz/togglz#115]
It would be a nice feature to if togglz was able to detect the csfr token that spring security generates and include when it it does POST. (http://docs.spring.io/spring-security/site/docs/4.0.x/reference/htmlsingle/#csrf)

This would prevent the invalid csfr token error that gets generated wich requires additional spring security config to disable csfr for /togglz/** url

**Comment by chkal** [comment]
I just implemented a first version of this feature. Would you perhaps give it a try? All you need to do is to update to the latest snaphots. You will find more details here:

http://www.togglz.org/download.html

This feature should work out of the box if you include the `togglz-spring-security` module. In the latest snapshots there should be an hidden input on the edit page which includes the CSRF token. Could you give it a try? Thanks!

**Comment by mayn** [comment]
Tested w/ togglz-spring-security-2.2.0-20150102.075831-4.jar
Behaved as expected.
1. with csfr disabled. No token was submitted as part of the post (as expected)
2. with csfr enabled. csrf token was submitted as part of post request. Various activation strategies posted successfully.
Thanks!

![togglz 115](https://cloud.githubusercontent.com/assets/1252884/5599574/6f18d948-927e-11e4-98e4-54c7f2825fb3.jpg)

**Comment by chkal** [comment]
Awesome. Thanks for testing. :)
