### ISSUE TITLE
Console shows features in differing order on refresh

### ISSUE THREAD

**Issue by ewoelfel** [togglz/togglz#1158]
Hello there,
we experienced the list of features changes order on refreshes. This might be due to the fact of using HashSets instead of LinkedHashSet.

If you have multiple instances of the same klnd (or over differing stages) it is hard to compare

https://github.com/togglz/togglz/pull/1157 tries to reduce the problem of switching order.

Thanks

**Comment by bennetelli** [comment]
Hey @ErikWoelfel2323,

I would like to add you as a maintainer as well. Would this be okay for you?

**Comment by ewoelfel** [comment]
@bennetelli I'd be honored. Thank you. I would also close that issue as it is fixed some months ago ;-)
