### ISSUE TITLE
Migrate Togglz Console to Bootstrap 3

### ISSUE THREAD

**Issue by chkal** [togglz/togglz#116]
We are currently using Bootstrap 2.x for the console. We should update this.

**Comment by dasniko** [comment]
I can do/help on this.
Just had a look into the code and it seems that it's not that much to do.
Any whishes/changes to the UI from your side? Or just updating the Bootstrap version and adjusting the classes?
I'd suggest to replace the icon-images with some kind of icon-font as glyphicons (come with bootstrap, but still separate files to include) or font-awesome.

**Comment by chkal** [comment]
That would be awesome! I don't think that there are any special additional wishes. It would be great if the UI would be responsive. And I agree that using Glyphicons or FontAwesome would be much better compared to the old images. Thanks a lot!
