### ISSUE TITLE
Custom Activation strategy is not getting registered

### ISSUE THREAD

**Issue by Rahil-Kanani** [togglz/togglz#118]
Hi,

I have created custom activation strategy. I have created one class by implementing ActivationStrategy interface. Wrote my business logic in isActive method.

Then created one folder services under META-INF and created one file with name org.togglz.core.spi.ActivationStrategy in it. Put fully qualified class name of custom strategy file like a.b.c.CustomStrategy in that file.

But I am not getting custom strategy registered and even Admin console stopped to work after this.

What wrong here I am doing?
Let me know if you need more details from my side.

Thanks
Jigar Shah

**Comment by chkal** [comment]
So you say the admin console is broken after you registered the custom strategy? Could you check the log files and post any exceptions you find?

**Comment by Rahil-Kanani** [comment]
Broken of Admin console is just one happening after that. My main concern is custom strategy is not getting registered so just want to know anything I am missing to configure or any workaround?

May be after resolving this issue Admin console can start but that is not concern right now. I was just letting you know.

Thanks
Jigar Shah

**Comment by chkal** [comment]
How do you know the strategy isn't registered without the admin console?

Please double check that the SPI file exists on the classpath and contains the FQCN of your implementation:

    META-INF/services/org.togglz.core.spi.ActivationStrategy

If you are using Maven, the location of the file must be:

    src/main/resources/META-INF/services/org.togglz.core.spi.ActivationStrategy

**Comment by Rahil-Kanani** [comment]
Yea...I am using Maven and crated file same as you mentioned but not working.
I have debugged code and checked DefaultActivationStrategyProvider file where it maintains collection of all provided. There I found that custom activation is not getting registered.

**Comment by chkal** [comment]
That's weird. There is no technical difference between the Togglz default strategies and custom strategies. They are all loaded using the ServletLoader Java API. See for example:

https://github.com/togglz/togglz/blob/master/core/src/main/resources/META-INF/services/org.togglz.core.spi.ActivationStrategy

https://github.com/togglz/togglz/blob/master/servlet/src/main/resources/META-INF/services/org.togglz.core.spi.ActivationStrategy

Please double check for typos in the file name, the directory structure and in the FQCN of your implementation. And make sure the file is available on the runtime classpath. If this still doesn't work, please provide a minimal sample app to reproduce this.

**Comment by Rahil-Kanani** [comment]
I checked everything again. File path is correct, file name is correct and I have mentioned FCQN of custom strategy class in that file.

**Comment by Rahil-Kanani** [comment]
Hi,

Thanks...my problem get resolved and strategy is being registered but still not able to open admin console.

**Comment by Rahil-Kanani** [comment]
Finally I found issue and Admin Console is working. Just one question regarding it.
In Admin Console, I am getting only All Features tab. How to get Performance and Usability tab in admin console?

**Comment by chkal** [comment]
These tabs are feature groups as described here:

http://www.togglz.org/documentation/feature-groups.html

**Comment by Rahil-Kanani** [comment]
Thank you very much for your support. All are cleared now.

**Comment by Rahil-Kanani** [comment]
Can you tell me how to separate Admin console for the application?

**Comment by chkal** [comment]
The admin console has been designed to be embedded into an existing application. But you can try to use the WAR overlay feature of the maven-war-plugin to merge it with an empty project and just include some configuration classes. That should work.

PS: Please ask such questions in the user forums. The issue tracker is not the intended place for this kind of discussion. Thanks.

**Comment by jayamathur** [comment]
@rahilk-ezdi Hi! Could you let me know what was the reason for the 403 Forbidden access error for your togglz console? I am struggling with the same error.

**Comment by chkal** [comment]
Which `UserProvider` are you using. Make sure that the `FeatureUser` which is returned from the `UserProvider` is a feature admin (`user.isFeatureAdmin() == true`).

**Comment by jayamathur** [comment]
I have overriden getUserProvider  with below method in the class that I am implementing TogglzConfig. But on startup, it finds featureUser as null. I am using togglz-spring-boot-starter

@Override
    public UserProvider getUserProvider() {
        return new UserProvider() {
            @Override
            public FeatureUser getCurrentUser() {             
                return new SimpleFeatureUser("admin", true);
            }
        };
    }

**Comment by chkal** [comment]
Hmmm... So the feature user is null? Where does it resolve to null? In the console servlet?

@marceloverdijk Could this relate to the spring-boot-starter?

**Comment by jayamathur** [comment]
@chkal Thanks for your reply! This issue is resolved for me now, I found that the project had a SingletonFeatureManagerProvider which was building the featureManager. It still had the userProvider set as NoOpFeatureUser. As soon as I changed that to my own userProvider it was resolved.

**Comment by jayamathur** [comment]
However, I have a new error now. I am not able to configure the stateRepository to my own database table. As long as I use InMemoryStateRepository, I can start the server and see the togglz admin console. But if I try to change the stateRepository to my project's database table, it throws null pointer exception.

I am upgrading this project from java 6 to 8, and we were using JDBCStateRepository(dataSource, "TABLE_NAME", false) to configure state reposiory earlier which was working fine. But that method is deprecated now and if I use JDBCStateRepository(dataSource, "TABLE_NAME"), it throws exceptions. Any ideas?

**Comment by chkal** [comment]
Please open a new issue for this and include the full stack trace.
