### ISSUE TITLE
Improve integration with Spring Security when CSRF protection is enabled

### ISSUE THREAD

**Issue by php-coder** [togglz/togglz#119]
It turns out that when I'm using Spring Security with Togglz and I'm enabling [CSRF protection](http://docs.spring.io/spring-security/site/docs/3.2.x/reference/htmlsingle/#csrf) then feature toggling stop to work.

Yes, I know about workarounds but may be Togglz may detect such situation and provide csrf token so it will work out of box with CSRF security? For example, we may try to lookup for token in request or session scopes or in headers. What do you think?

**Comment by chkal** [comment]
This is already implemented and available in the current snapshots. See #115.
