### ISSUE TITLE
Maven dependency for togglz project jar does not work

### ISSUE THREAD

**Issue by shadowsak** [togglz/togglz#120]
[ERROR] Failed to execute goal on project Launcher: Could not resolve dependencies for project 
Could not find artifact org.togglz:togglz-project:jar:2.2.0-SNAPSHOT in sonatype-oss-snapshots (https://oss.sonatype.org/content/repositor
ies/snapshots) -> [Help 1]

<repository>
		    <id>sonatype-oss-snapshots</id>
		    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
		    <releases>
		      <enabled>true</enabled>
		    </releases>
		    <snapshots>
		      <enabled>true</enabled>
		    </snapshots>
  	</repository>

**Comment by chkal** [comment]
The snapshots are definitely in the OSS repository:

https://oss.sonatype.org/content/repositories/snapshots/org/togglz/togglz-core/2.2.0-SNAPSHOT/

Please double check the dependency coordinates and the repository URL.

If it still doesn't work, please post your pom and the full error message to use togglz-users forum:

https://groups.google.com/forum/?fromgroups#!forum/togglz-users
