### ISSUE TITLE
Improve efficiency for getMetaData() on EnumBasedFeatureProvider

### ISSUE THREAD

**Issue by RichSteele** [togglz/togglz#121]
See discussion at https://groups.google.com/d/msg/togglz-users/XYDLVlsvQW8/Fx5-RUy7QJ0J

**Comment by atlanteh** [comment]
Shouldn't this one be closed? I see a commit that fixes this issue.

**Comment by chkal** [comment]
Yes, I think this one is fixed already! Thanks!
