### ISSUE TITLE
Refactor FileBasedStateRepository to allow for other kinds of non-file based property providers

### ISSUE THREAD

**Issue by RichSteele** [togglz/togglz#124]
See https://groups.google.com/forum/?fromgroups#!topic/togglz-dev/pGk4qGX2bN4

In short, projects wanting to use properties from other sources than files cannot use the FileBasedStateRepository nor extend it, resulting in duplicated logic for parsing the property keys.  We need to extract the property handling portions of FileBasedStateRepository into a new PropertyBasedStateRepository that uses a PropertySource interface (which ReloadablePropertiesFile implements) for getting and setting the property values.

**Comment by chkal** [comment]
PR applied. ;)
