### ISSUE TITLE
[feature idea]: Rework @RunWith(FeatureVariations.class) into a @Rule

### ISSUE THREAD

**Issue by danhaywood** [togglz/togglz#131]
I really like the testing support you've implemented in togglz, and the FeatureVariations concept is smart and elegant.  It'd be nice if this could be reworked into a @Rule, though, perhaps an enhancement to TogglzRule?

My main thought was that the TogglzRule#apply(...) could basically call base#evaluate() multiple times, one for each variation.  The logic that works out the different variations (that I presume is part of the FeatureVariations runner) would just move to drive a loop inside of #apply().

The API would be something like:

@Rule
  public TogglzRule togglzRule = TogglzRule.allEnabled(MyFeatures.class)
                                                                        .withVariations()
                                                                         .enable(MyFeatures.F1)
                                                                         .vary(MyFeatures.F2)
                                                                         .vary(MyFeatures.F3);

or something like that.

**Comment by chkal** [comment]
Very interesting idea. I actually like JUnit rules very much and always try to prefer them over `@RunWith()`. However, I'm not sure if it is possible to call base#evaluate() multiple times to create "virtual test results" that are correctly displayed in the IDE.

However, if it works, I agree that implementing a rule would be awesome. Any interest in working on a prototype for this? ;)

**Comment by danhaywood** [comment]
Hi Christian, glad you like the idea.  Hadn't thought about the impact to
an IDE, but I imagine/hope that it would just be a test from its point of
view.  Have to just try it out.
Yes, I'll see if I can work on a prototype in the next week or so.  Should
be interesting to try something out.
Cheers
Dan
PS: FYI am using using togglz for a new "addon" for Apache Isis, see
github.com/isisaddons/isis-module-togglz, isisaddons.org and isis.apache.org

**Comment by chkal** [comment]
The RunAs mechanism basically allows to run tests multiple times in a different "environment". So if you configure 4 variations, each test will be reported (in IDEs and the resulting XML files) as 4 "virtual" tests. That's a really nice JUnit feature.

However, maybe that's possible with rules too. I don't know actually. But it is worth a try.

You will find an Eclipse code format profile in the source root. If you create a prototype, it would be great if you would use it.

To be honest, I didn't know about Apache Isis. But it looks very interesting. I'll have a look at it as soon as I find some time. It's awesome that you created a Togglz plugin for it. Thanks for that. :)

**Comment by danhaywood** [comment]
The add-on for Isis is now complete, pretty much... https://github.com/isisaddons/isis-module-togglz 

I've moved onto IntelliJ after more than a decade using Eclipse... but I have Eclipse installed still and will use it for this prototyping.

Cheers

**Comment by chkal** [comment]
Great. I'll give the plugin a try as soon as I get the chance to play with Isis.

I also switched to IntelliJ some time ago. I just imported the Eclipse code style profile into IntelliJ. So that should be fine.
