### ISSUE TITLE
togglz-spring 2.2.0 not in MVN repos

### ISSUE THREAD

**Issue by Iker-Jimenez** [togglz/togglz#139]
last version I can see is 2.1.0.
See http://mvnrepository.com/artifact/org.togglz/togglz-spring

**Comment by chkal** [comment]
The artifact name for the Spring module has changed. Just use `togglz-spring-web` instead of `togglz-spring` and it should work fine.

See the updating notes for details:

http://www.togglz.org/updating-notes.html

**Comment by Iker-Jimenez** [comment]
Nice, I actually asked for this functionality some time ago. I think you need to update http://www.togglz.org/documentation/installation.html then.

**Comment by chkal** [comment]
Thanks. Looks like I missed this part of the documentation.

Should be fixed now:

https://github.com/togglz/togglz-site/commit/2d8c3cee8047ce2bfc6f4fb4038c816deb46d191
