### ISSUE TITLE
Does Togglz support a multiple state repositories?

### ISSUE THREAD

**Issue by marceloverdijk** [togglz/togglz#145]
Does Togglz support a CompositeStateRepository which e.g. first uses a JDBCStateRepository but if it cannot find the feature it will try e.g. a FileBasedStateRepository?

Use case is that via the JDBCStateRepository a particular feature is searched for the logged in user.
But if the feature value is not stored for the user we want to fall back on default settings in file.

**Comment by chkal** [comment]
Have a look here:

https://github.com/togglz/togglz/blob/master/core/src/main/java/org/togglz/core/repository/composite/CompositeStateRepository.java

:)

**Comment by marceloverdijk** [comment]
Thanks! I was looking at 2.0.0 apidocs instead of latest 2.2.0.
