### ISSUE TITLE
Provide more control over the Admin Console's authentication mechanism

### ISSUE THREAD

**Issue by marceloverdijk** [togglz/togglz#151]
Currently the authentication of the Admin Console is tight to the `FeatureManager`s `UserProvider`.

I quick (short-term?) solution would be to make if configurable to completely bypass the the check in the `TogglzConsoleServlet` to see if user is admin (and let apps take care of that in their own way).
This would also be extremely useful when providing a `NoOpUserProvider`. In that case you don't have to provide a custom `UserProvider` to just provide a simple user with admin functionality.

Another (long-term?) solution would be as @chkal suggested is to have a plugable authentication strategy.

Personally I would be fine with option 1 :-)

If interested I can provide a PR which introduces a `is_feature_admin` servlet init-param which can be set to true to by bypass current check from current user.

Another approach would be to make something like `getUserProvider` available in the `FeatureManager` interface, and in case it is a `NoOpUserProvider` the `TogglzConsoleServler` reckons it's alright. Sounds also like a decent solution imo.

Adding this make my Spring Boot Auto Configuration a little bit easier.
When the user does not provide a `UserProvider` I want to create a `NoOpUserProvider` but this causes the admin console unavailable.

**Comment by chkal** [comment]
I just committed a minor change which is basically a very lightweight way for option 2.

Basically users can now simply extend `TogglzConsoleServlet` and overwrite the `isFeatureAdmin` method. I actually think this is the most flexibel solution. IMO using a custom authentication strategy for the console servlet is actually a very rare case. But now users can simply extend the servlet and implement their own strategy. Example:

```java
public class NoAuthTogglzConsoleServlet extends TogglzConsoleServlet {

    @Override 
    protected boolean isFeatureAdmin(HttpServletRequest request) {
        return true;
    }
    
}
```

What do you think? Would this fit your needs?

However, we could think about a more flexibel way of handling the authentication for the admin console which doesn't necessarily require a proper UserProvider.

**Comment by marceloverdijk** [comment]
Yes it's a good start :-)

For me personally a more flexible handling of authentication should not be the scope of Togglz.
I think that's something for the security framework used in the app itself.
Therefore the ability to bypass the `UserProvider` should be enough imo.

**Comment by marceloverdijk** [comment]
I will use something like this for the Boot auto configuration

```
        @Bean
        public ServletRegistrationBean togglzConsole() {
            String path = properties.getConsole().getPath();
            String urlMapping = (path.endsWith("/") ? path + "*" : path + "/*");
            TogglzConsoleServlet servlet;
            if (userProvider instanceof NoOpUserProvider || !properties.getConsole().isRequiresFeatureAdmin()) {
                servlet = new TogglzConsoleServlet() {
                    @Override
                    protected boolean isFeatureAdmin(HttpServletRequest request) {
                        return true;
                    }
                };
            } else {
                servlet = new TogglzConsoleServlet();
            }
            return new ServletRegistrationBean(servlet, urlMapping);
        }
```

**Comment by chkal** [comment]
Ok, great, this should work fine I think.

BTW: I'm just a bit concerned that the admin console is not protected by any authentication mechanism by default. Isn't this a bit dangerous? How do other Spring Boot auto configuration features support something like this?

**Comment by marceloverdijk** [comment]
Yes that's a good point. I will look into it as the default endpoints in Boot are also protected I believe.

**Comment by chkal** [comment]
I'll close this one as #152 and 3d7f86f0ae5c93affe981f8a3ea67a4499fb31ef now provide much more control...
