### ISSUE TITLE
FeatureManager is not found in jetty 9

### ISSUE THREAD

**Issue by MinjieTao** [togglz/togglz#171]
Hi,

I used togglz in my web service which used spring framework. However, I found that the togglz works in jetty8 but it shows error as below.
> java.lang.IllegalStateException: Could not find the FeatureManager. For web applications please verify that the TogglzFilter starts up correctly. In other deployment scenarios you will typically have to implement a FeatureManagerProvider as described in the 'Advanced Configuration' chapter of the documentation.

All the code and java version is the same. 
By the way, I used togglzConfig to generate a FeatureManager.

Does anyone have some idea about it :)

**Comment by chkal** [comment]
Togglz uses a `web-fragment.xml` file for automatic registration of required filters during application startup. Perhaps you need some additional dependency for making this work in Jetty9? I vaguely remember that there was some kind of jetty-plus dependency for additional features.

**Comment by MinjieTao** [comment]
I solved this problem by add configuration below to web.xml.
```
<!-- Togglz configuration for Servlet 2.5 and earlier -->
<filter>
  <filter-name>TogglzFilter</filter-name>
  <filter-class>org.togglz.servlet.TogglzFilter</filter-class>
</filter>
<filter-mapping>
  <filter-name>TogglzFilter</filter-name>
  <url-pattern>/*</url-pattern>
</filter-mapping>
```
However, I don't know why because jetty 9.3.6  supports Servlet 3.1 as showed in [https://en.wikipedia.org/wiki/Jetty_(web_server)](url).

**Comment by chkal** [comment]
Hmmm. In this case it looks like your Jetty setup doesn't support web fragments for some reason. I'm not very familiar with Jetty, so I don't think I can help here. :-(

**Comment by MinjieTao** [comment]
Anyway, thank you for your reply!
