### ISSUE TITLE
SpringSecurityUserProviderConfiguration errantly triggers during autoconfiguration

### ISSUE THREAD

**Issue by wgorder** [togglz/togglz#173]
If you have spring-security on the classpath but do not include 

```
		<dependency>
			<groupId>org.togglz</groupId>
			<artifactId>togglz-spring-security</artifactId>
			<version>2.3.0.RC2</version>
		</dependency>

```

Autoconfiguration will fail due to the way that the Conditional Beans are currently set up.  In my case I do not wish to use Togglz security at all.  Therefore the below block of code should be conditional on something that is brought in with the togglz-spring-security artifact to prevent it from activating otherwise.
I think   `@ConditionalOnClass({EnableWebSecurity.class, AuthenticationEntryPoint.class, SpringSecurityUserProvider.class})` would do the trick.

```
    @Configuration
    @ConditionalOnClass({EnableWebSecurity.class, AuthenticationEntryPoint.class})
    @ConditionalOnMissingBean(UserProvider.class)
    protected static class SpringSecurityUserProviderConfiguration {

        @Autowired
        private TogglzProperties properties;

        @Bean
        public UserProvider userProvider() {
            return new SpringSecurityUserProvider(properties.getConsole().getFeatureAdminAuthority());
        }
    }
```

**Comment by marceloverdijk** [comment]
What error are you getting? Would you be able to post a stacktrace?

**Comment by marceloverdijk** [comment]
Yes I think you are right about adding the `SpringSecurityUserProvider` class to the conditional on class.
I will push a change to `master` shortly.

**Comment by marceloverdijk** [comment]
Change is pushed to `master` and will be available in latest snapshot. Please watch https://travis-ci.org/togglz/togglz/builds/141267422.
Thanks for reporting this @wgorder!
