### ISSUE TITLE
Autoconfiguration fails silently when FeatureProvider is not provided

### ISSUE THREAD

**Issue by wgorder** [togglz/togglz#174]
This is regarding Spring Boot autoconfiguration.  Some sort of exception should be thrown if the user does not configure a FeatureProvider with any of the methods provided.  I tested this and my app failed to start and gave no indication, the problem was no FeatureProvider was provided.

**Comment by marceloverdijk** [comment]
Which version of the Togglz starter are you using? We discussed this behavior on gitter and other people didn't want an exception and I do agree honestly.
What kind of error did you get that prevented you from starting your app?

**Comment by wgorder** [comment]
Well connections to AMPQ and some other weird things happened.  The tomcat container then blew up with all sorts of weird SL4J errors and other things.  Nothing in the log though indicated the problem was this configuration.  However adding the FeatureProvider fixed everything.  The docs do cover that you need to provide one, however I think its not good that if one is not provided things can potentially fail in strange ways with no indication as to the cause.  I think that since it is required the user would want to know and fail fast if they had forgotten it.  My 2cents.

**Comment by marceloverdijk** [comment]
Hmm, is this a project you can share? I'm really wondering what kind of errors you get...
I don't understand what the missing `FeatureProvider` can cause the AMPQ connection failures, because when you don't provide the `FeatureProvider` or `togglz.feature-enums` property the whole Togglz Auto Configuration is ignored (not executed) as can be seen here: https://github.com/togglz/togglz/blob/master/spring-boot-starter/src/main/java/org/togglz/spring/boot/autoconfigure/TogglzAutoConfiguration.java#L66

Are you creating some Togglz releated beans manually?

**Comment by marceloverdijk** [comment]
@wgorder I'm still unsure why you get this error, but I made some changes to `master` anyway.
When adding the `togglz-spring-boot-starter` it will mean Togglz will be now be initialised even when no `FeatureProvider` is provider or the `togglz.feature-enums` property is set.
The auto configuration will automatically create a dummy feature provider and writes a warning to the log.

Can you please watch https://travis-ci.org/togglz/togglz/builds/141553973 and try with the latest snapshot?

I've also created a sample demonstrating the behaviour: https://github.com/togglz/togglz-samples/tree/master/spring-boot-no-feature-provider-or-feature-enums

**Comment by wgorder** [comment]
@marceloverdijk  Unfortunately it is a big project, and I cannot share it,  there are lots of moving parts.   I did not take the time to figure out  what the cause was exactly, but I do know what fixed it was adding the  bean specified in the docs.

```
@Bean
public FeatureProvider featureProvider() {
    return new EnumBasedFeatureProvider(MyFeatures.class);
}
```

That is the only thing I had added to my configuration.  I did not override anything else. 

You can feel free to close this if you would like.  I think as long as a WARNING is provided I think that is sufficient to address my issue.

**Comment by marceloverdijk** [comment]
OK I will close it now as we changed the behaviour anyway.
