### ISSUE TITLE
Encoding issue in Togglz Console

### ISSUE THREAD

**Issue by chkal** [togglz/togglz#175]
It looks like non-ASCII characters are broken when saved via the edit page. According to feedback from the users lists calling `HttpServletRequest.setCharacterEncoding("UTF-8")` fixes this.

**Comment by dasniko** [comment]
Are there any steps to reproduce?
Just entered a few non-ASCII characters as username and it worked fine.

**Comment by error418** [comment]
I also tried to reproduce this issue some time ago with no luck.

Maybe of would be a good idea to use GitHub issue templates to remind the reporter to supply such information on issue creation

**Comment by chkal** [comment]
Yeah, I agree that we may have to improve the issue template. But this bug was brought up on the mailing list and therefore I don't have more information.

But if we cannot reproduce this issue, let's just close it. If it is really a bug, someone will open a new issue at some point.
