### ISSUE TITLE
Logging when a Toggle state is changed

### ISSUE THREAD

**Issue by gpt559** [togglz/togglz#176]
I'm trying to find a way to log when a toggle is turned on/off from the admin console. To start using togglz in production I need to be able to have a transaction logged that says Who made What change. 

I don't see an easy way to AOP so I was wondering if someone could point me in the right direction. 

I was looking at the EditPageHandler.java::process method
https://github.com/togglz/togglz/blob/41fd464c7f1fb2b626748b1577c61691bc470b98/console/src/main/java/org/togglz/console/handlers/edit/EditPageHandler.java
```
// POST requests for this feature
        if ("POST".equals(request.getMethod())) {

            featureModel.restoreFromRequest(request);

            // no validation errors
            if (featureModel.isValid()) {

                FeatureState state = featureModel.toFeatureState();
                featureManager.setFeatureState(state);
                response.sendRedirect("index");

            }
```

Maybe turn that bit of code into a method that we could put some easy AOP on. Thoughts?

**Comment by chkal** [comment]
I usually recommend to create a custom state repository to log feature state modifications.

See for example:

https://groups.google.com/forum/m/#!topic/togglz-users/M1Bh3yMTgvU

**Comment by gpt559** [comment]
@chkal that worked. I didn't do that before because I wasn't sure if I could get the current user, but that ended up being moot since I could just pull that information from the SecurityContextHolder.

Thanks!
