### ISSUE TITLE
Load custom activation strategies through Spring

### ISSUE THREAD

**Issue by charithdesilva** [togglz/togglz#177]
Hi 

I'm building up a mini framework to overload activation strategies one after another (AND or OR relationship). I found it'd be really helpful if I can initiate strategies through Spring rather SPI used currently. I just started looking into actual implementation, appreciate if you have any insight on this?

Charith

**Comment by chkal** [comment]
There is an SPI for that:

https://github.com/togglz/togglz/blob/master/core/src/main/java/org/togglz/core/activation/ActivationStrategyProvider.java

IIRC you can set the strategy if you build the FeatureManager using the FeatureManagerBuilder.

**Comment by charithdesilva** [comment]
I'm using FeatureManagerFactory to load FeatureManager (initiate through spring context). FeatureManager doesn't have a setter to add activation strategies dynamically.

**Comment by charithdesilva** [comment]
And there's no way to inject strategy provider into FeatureManagerFactory either :(

**Comment by chkal** [comment]
If you have an "advanced setup", I recommend to use FeatureManagerBuilder instead as this is the "primary" way of creating a FeatureManager and it doesn't depend on Spring. You could use Spring's Java Config style for that. So basically create a method annotated with `@Bean`.

**Comment by chkal** [comment]
FeatureManagerFactory is primarily used for XML configuration. And nobody wants that. ;-)

**Comment by charithdesilva** [comment]
Spot on Chris. Cheers! I'm sharing my implementation for future users. 

```
@Configuration
public class TogglzConfig {
	
	@Autowired
	List<ActivationStrategy> activationStrategies;
	
	@Autowired
	private StateRepository stateRepository;
	
	@Autowired
	private UserProvider userProvider;
	
    @Bean
    public FeatureManager featureManagerBuilder() {
    	
    	FeatureManagerBuilder featureManagerBuilder =  new FeatureManagerBuilder().
    			featureEnum(MyFeatures.class).
    			stateRepository(stateRepository).
    			userProvider(userProvider);
    	
    	if (activationStrategies != null) {
    		for (ActivationStrategy strategy : activationStrategies) {
    			featureManagerBuilder.activationStrategy(strategy);
    		}
    	}
    	
    	return featureManagerBuilder.build();		
    }
}
```

**Comment by chkal** [comment]
Great! That looks perfect. Actually this is my preferred way to bootstrap Togglz. Use the FeatureManagerBuilder to create a manager, let it be managed by the framework of your choice and Togglz will automatically discover it using the corresponding framework integration modules. :-)
