### ISSUE TITLE
Documentation: How are feature groups configured without console?

### ISSUE THREAD

**Issue by C-Otto** [togglz/togglz#180]
The page regarding [feature groups](http://www.togglz.org/documentation/feature-groups.html) mentions how to define feature groups, but does not explain how these are configured outside of the admin console. As I configure using Archaius, I have no idea how to make use of feature groups.

**Comment by chkal** [comment]
Just define the group and place them on your enum fields. The console should automatically display them correctly. You don't need any extra step to configure the console.

**Comment by C-Otto** [comment]
@chkal I was asking how to make use of feature groups **without** using the console.

**Comment by chkal** [comment]
Oh sorry, I misunderstood your question. Currently feature groups are just used for a visual grouping in the admin console. So if you are not using the admin console, there is very little use for feature groups.

**Comment by C-Otto** [comment]
I see. I'd prefer this to be stated somewhere in the documentation.

**Comment by chkal** [comment]
If you have any idea how to improve this section of the documentation, feel free to open a pull request. The site source is freely available:

https://github.com/togglz/togglz-site/blob/master/documentation/feature-groups.html.haml
