### ISSUE TITLE
togglz's support for junit @BeforeClass and @AfterClass is weird

### ISSUE THREAD

**Issue by zhangchi** [togglz/togglz#185]
Hi,

Here is a simple test we did, we are running with annotation `@RunWith(FeatureVariations.class)`: 

``` java
@Variations
public static VariationSet<EFeature> getPermutations() {
    return VariationSetBuilder.create(EFeature.class).vary(EFeature.NEW_FEATURE);
}
```

Our test is running in embedded glassfish as an EJB integration test. In our test, we simple do the following:

``` java
@BeforeClass
public static void setUpClass() {
    logger.log(Level.INFO, "Setup Class got called ===================> ");
}

@AfterClass
public static void tearDownClass() {
    logger.log(Level.INFO, "Teardown Class got called ===================> ");
}
```

This is what we got:

```
[#|2016-11-09T10:31:24.291-0800|INFO|undefined 0.0|BatchUploadingServicesITTest|_ThreadID=1;_ThreadName=main;_TimeMillis=1478716284291;_LevelValue=800;|Setup Class got called ===================> |#]
[#|2016-11-09T10:31:18.925-0800|INFO|undefined 0.0|BatchUploadingServicesITTest|_ThreadID=1;_ThreadName=main;_TimeMillis=1478716278925;_LevelValue=800;|Setup Class got called ===================> |#]
[#|2016-11-09T10:31:18.985-0800|INFO|undefined 0.0|BatchUploadingServicesITTest|_ThreadID=1;_ThreadName=main;_TimeMillis=1478716278985;_LevelValue=800;|Setup Class got called ===================> |#]


Starting EJBTest
[#|2016-11-09T10:31:24.227-0800|INFO|undefined 0.0|BatchUploadingServicesITTest|_ThreadID=1;_ThreadName=main;_TimeMillis=1478716284227;_LevelValue=800;|Teardown Class got called ===================> |#]
[#|2016-11-09T10:31:26.762-0800|INFO|undefined 0.0|BatchUploadingServicesITTest|_ThreadID=1;_ThreadName=main;_TimeMillis=1478716286762;_LevelValue=800;|Teardown Class got called ===================> |#]

[#|2016-11-09T10:31:26.762-0800|INFO|undefined 0.0|BatchUploadingServicesITTest|_ThreadID=1;_ThreadName=main;_TimeMillis=1478716286762;_LevelValue=800;|Teardown Class got called ===================> |#]
```

So, two questions over here:

1. Based on my understanding, the whole unit test should only be run twice since I only did the variation on one Feature. How does the logging indicating Before/After class methods get called three times?
2. Looks like all the BeforeClass methods got called together at beginning and then all the After class methods got executed. This could be an issue, since most of the basic configuration could be configured at BeforeClass method and then after all the tests are done, AfterClass method will clean up this config. Having BeforeClass methods running all together will only create duplicate Entries in the database or duplicateEntry exception if there is an uniqueKey.

Looking forward to any comments.

**Comment by chkal** [comment]
It is very difficult to read your post especially because of the broken formatting. Could you perhaps fix this? I think this will help to understand your setup better.

**Comment by neocotic** [comment]
I've reformatted the original post in an attempt to improve readability and hopefully it can get a response now. @zhangchi, is this still an issue?

**Comment by neocotic** [comment]
I've just taken a look at the code and I believe that the reason that it's being called numerous times is that `FeatureVariations` appears to be extending `Suite`, which is designed for collecting multiple different classes, so it's setting up the test class for each child runner in the suite.

I propose that we change it to extend from `Runner` instead of `Suite`.

**Comment by neocotic** [comment]
I've opened PR #200 with an attempt to fix this bug.

**Comment by chkal** [comment]
Actually the current implementation is similar to JUnit's `Parameterized` runner, which I guess behaves the same way as the Togglz runner. So I'm not completely sure if the described behavior is really a bug or expected.

**Comment by chkal** [comment]
Closing because no further feedback received.

**Comment by darnoldt** [comment]
I came across the very same problem. I think the reason for this misbehaviour is, that the `VariationRunner` does not override the method `protected Statement classBlock(RunNotifier notifier)` 
from the base class as does the `BlockJUnit4ClassRunnerWithParameters`.

**Comment by chkal** [comment]
I just had another look at this issue. I think I finally fixed the bug that caused `@BeforeClass` and `@AfterClass` to be invoked twice. See 76227b471023cbb417ac4fcf0fadca2fbbe03bfe for details. It would be great if anyone could confirm the fix.

**Comment by chkal** [comment]
I just discovered that there were some issues with the automatic snapshot deployment. But that's fixed now. So the latest version of `2.6.0-SNAPSHOT` will contain the fix. See [this page](https://www.togglz.org/download.html) for details about how to test the snapshots.
