### ISSUE TITLE
Upgrade the mongo module to Mongo 3 

### ISSUE THREAD

**Issue by kevinstembridge** [togglz/togglz#187]
I've just come across Togglz and introduced it into an application that uses Mongo with version 3.3.0 of the Mongo Java driver. 

The MongoStateRepository references a method that no longer exists in the newer version of the driver. The Db.authenticate method has been removed.

    
    protected DBCollection togglzCollection() {
        DB db = mongoClient.getDB(dbname);
        db.setWriteConcern(writeConcert);
        if (username != null && password != null) {
            db.authenticate(username, password);
        }
        return db.getCollection(collection);
    }

Any chance you could upgrade the Mongo Driver version?

**Comment by chkal** [comment]
Hey @kevinstembridge,

I'm fine with updating the MongoDB driver version. I'm just wondering why this method has been removed. Is the authentication handled now in a different way? Any insights about that?

Anyway, updating the driver would be good. Any help with this is highly appreciated. 

https://github.com/togglz/togglz/wiki/Contributing

**Comment by kevinstembridge** [comment]
Hi @chkal ,

I think they have a more sophisticated mechanism for authentication now and as far as I'm aware it's all taken care of at the MongoClient level. Since the MongoClient is provided to the MongoStateRepository I think it would be safe to remove authentication from the repository altogether.

I'm happy to take a look at providing a pull request. I'll let you know how I get on.

Cheers,
Kevin

**Comment by chkal** [comment]
I did a quick check and it looks like the authentication API changed significantly:

http://mongodb.github.io/mongo-java-driver/3.0/driver/reference/connecting/authenticating/

I guess it should remove username/password from the MongoStateRepository and use MongoCredential instances instead which could be configured by the builder. This way the user could use any authentication method required.

**Comment by kevinstembridge** [comment]
Do you have any hints for writing integration tests? I couldn't see how the existing MongoStateRepository is tested.

**Comment by chkal** [comment]
Unfortunately there are no integration tests for the MongoDB integration at the moment. Not sure how this could work. Does the MongoDB driver support something to write test without talking to a real MongoDB instance?

**Comment by kevinstembridge** [comment]
I'll see what I can do with Fongo. 
https://github.com/fakemongo/fongo

**Comment by chkal** [comment]
Ok, great! :+1:

**Comment by chkal** [comment]
Fixed with #191
