### ISSUE TITLE
Expose admin-console in Spring Boot on management.port

### ISSUE THREAD

**Issue by jkubrynski** [togglz/togglz#190]
Currently, the `TogglzConsoleServlet` is exposed on the application port. It makes sense to use management port, which is used for configuration/management stuff. You can check this SO answer:
http://stackoverflow.com/questions/40851274/expose-togglz-admin-console-in-spring-boot-on-management-port

**Comment by chkal** [comment]
Interesting idea. However, I'm not sure if this can be cleanly integrated into the Togglz Spring module. 

@marceloverdijk: Any thoughts on that?

**Comment by marceloverdijk** [comment]
Hmmm, indeed an interesting idea.
Looking at the stackoverflow implementation it feels a bit hackish... I will have a look.

**Comment by chkal** [comment]
Would be interesting to know why it has to be hackish especially for the Togglz servlet. Looks like it has something to do with the way the servlet parses the URLs.

**Comment by marceloverdijk** [comment]
I had a discussion about this on the Boot gitter forum and there is an alternative available:

```
@marceloverdijk 13:49
When adding a ServletRegistrationBean bean to my Boot app to register a custom servlet would it be possible to bind it to the management port?

@wilkinsona 14:22
Yes, as long as you declare the bean in a @ManagementContextConfiguration class that’s registered in spring.factories

@marceloverdijk 14:26
hmmm, let me explain my use case a little bit
The Togglz Boot Starter provided the option to automatically configure the Togglz Console servlet
By default this is bound to the application context
One of the users came with the question to bind it to the manamgement port; which makes sense of course
I was thinking to make this configurable.....

@marceloverdijk 14:33
We currently do that in https://github.com/togglz/togglz/blob/master/spring-boot-starter/src/main/java/org/togglz/spring/boot/autoconfigure/TogglzAutoConfiguration.java#L224
In a TogglzConsoleConfiguration to be precise
Maybe I should second TogglzConsoleManagementContextConfigurationclass with the @ManagementContextConfiguration
and only enable one of the 2 using a use-management-port property
Does that make sense?

@wilkinsona 14:39
Yeah, I think it does
```

I will look into it shortly.

**Comment by chkal** [comment]
Awesome! Great!

**Comment by jkubrynski** [comment]
@chkal Hacking was required due to way Togglz checks which handler to choose. With MvcEndpoint Servlet path contains whole url (servlet path == request url), so it ends up with togglz servlet adding "/index" all the time, resulting in "togglz/index/index/index/index/index/index/index...."

**Comment by marceloverdijk** [comment]
@jkubrynski so looking at an alternative `@ManagementContextConfiguration` configuration bean might be a better fit...

**Comment by jkubrynski** [comment]
@marceloverdijk totally right - it looks much better

**Comment by chkal** [comment]
Hey @jkubrynski,

> With MvcEndpoint Servlet path contains whole url (servlet path == request url),

I see why the handler matching won't work in this case. But I'm not sure if Spring is allowed to return the full request URI with `HttpServletRequest.getServletPath()`. 

The Javadocs of `HttpServletRequest` state:

> Returns the part of this request's URL that calls the servlet. This path starts with a "/" character and includes either the servlet name or a path to the servlet, but does not include any extra path information or a query string.

What do you think? Isn't this a bug on the Spring side?

**Comment by chkal** [comment]
From the Servlet 3.1 specification (section 3.5):

> **Servlet Path:** The path section that directly corresponds to the mapping which
activated this request. This path starts with a ’ / ’ character except in the case
where the request is matched with the ‘ /* ’ or ““ pattern, in which case it is an
empty string.

**Comment by jkubrynski** [comment]
@chkal It happens only when I use the `MvcEndpoint` so let's check how the situation will look like with `ManagementContextConfiguration`

**Comment by marceloverdijk** [comment]
I have just pushed a change to `master` so the admin console is  - by default! - exposed on the management port (if there is management port defined).

This behaviour can be disabled by setting the application property `togglz.console.use-management-port: false`.

I've tested the all the scenario's myself and it works fine, but it would be nice if someone can verify as well... @jkubrynski this functionality will be available in 2.4.0-SNAPSHOT as soon as the Travis build finishes.

**Comment by marceloverdijk** [comment]
@chkal I created https://github.com/togglz/togglz-site/tree/190_expose_admin_console_on_management_port for updating the documentation regarding this new `use-management-port` property. We must not forget to merge that in with `2.4.0` release.

**Comment by chkal** [comment]
@marceloverdijk: Awesome! Thank you so much for implementing this. I really think that this makes sense and will be very useful!

**Comment by marceloverdijk** [comment]
Thanks to @jkubrynski for the suggestion 👍 
Build https://travis-ci.org/togglz/togglz/builds/181099700 has passed so it should be in the snapshot now.

**Comment by chkal** [comment]
@marceloverdijk Thanks for preparing the documentation update. I guess we need some kind of process how to update the site with regard to new features which will be part of the next release.

**Comment by jkubrynski** [comment]
@marceloverdijk I've tested it and it's almost great :) Togglz console runs on management-port, however you don't include `management.context-path` while registering the servlet. When you set `management.context-path` to `:/manage` then console should be mapped to "host:management_port/manage/togglz-console"

**Comment by marceloverdijk** [comment]
@jkubrynski thx for feedback will add that as well!

**Comment by marceloverdijk** [comment]
@jkubrynski `managememnt.context-path` is now added to the console path. Will be part in snapshot with build https://travis-ci.org/togglz/togglz/builds/181173516

**Comment by jkubrynski** [comment]
@marceloverdijk I've added a comment here: https://github.com/togglz/togglz/commit/cb85ff021c2915081e3b2f0109a8eb4ee8fa58fb#commitcomment-20067766

**Comment by marceloverdijk** [comment]
thx @jkubrynski I will have a look later today!

**Comment by marceloverdijk** [comment]
@jkubrynski I pushed a fix, please try again.

**Comment by jkubrynski** [comment]
@marceloverdijk Works great! Looking forward to seeing RC :)

**Comment by marceloverdijk** [comment]
@jkubrynski I just pushed another change, would you be able to test it again to verify it works in your setup?

**Comment by jkubrynski** [comment]
If you mean version `2.4.0-20161206.125550-13` then I confirm it's working correctly

**Comment by marceloverdijk** [comment]
Yes that's the version; thanks for confirming :+1:
