### ISSUE TITLE
Add new features at runtime

### ISSUE THREAD

**Issue by tristobal** [togglz/togglz#198]
Hello.

I'm working in a project that manage features in database, but I need to add new features at runtime. Is it possible? Looking the implementations of FeatureProvider, the method getFeatures of EnumBasedFeatureProvider and PropertyFeatureProvider returns an unmodifiable collection of features.

Thanks in advance.

**Comment by hexmind** [comment]
Hi, are you sure you need runtime created toggle?
Is your feature created in runtime too?

**Comment by tristobal** [comment]
Yes.

I will create some record that needs specifics features for them =/

**Comment by neocotic** [comment]
@tristobal Why not simply create your own implementation of `FeatureProvider` which is backed by the database? It seems to be the perfect place to start. Here's the JavaDoc for the interface:

> Implementations of this interface are responsible for providing feature base data. The default implementation EnumFeatureMetaData for example is used if features a defined using a feature enum. Users can provide custom implementations to support something like a dynamic list of features.

**Comment by chkal** [comment]
@tristobal I agree with @neocotic. In your case it would perfectly make sense to provide your own `FeatureProvider` implementation which gives you all the flexibility you will need.
