### ISSUE TITLE
Togglz Console in 2.4 Spring Boot

### ISSUE THREAD

**Issue by markdav** [togglz/togglz#203]
Is there an undocumented breaking change between 2.3 and 2.4?  Taking a boot project with <togglz.version>2.3.0.Final</togglz.version>

```
        <!-- Togglz Starter -->
        <dependency>
            <groupId>org.togglz</groupId>
            <artifactId>togglz-spring-boot-starter</artifactId>
            <version>${togglz.version}</version>
        </dependency>

        <!-- Togglz Admin Console (optional) -->
        <dependency>
            <groupId>org.togglz</groupId>
            <artifactId>togglz-console</artifactId>
            <version>${togglz.version}</version>
        </dependency>
```

application.properties:

```
togglz.console.enabled=true
togglz.console.path=/toggles
togglz.console.secured=false

```
On startup we see:

`2017-03-02 12:36:10.323  INFO 10067 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'togglzConsoleServlet' to [/toggles/*]`

And the console works just fine.

However.. switch the version to 2.4.0.Final and you don't get the ServletRegistrationBean mapping and hence no working console.  I haven't gotten to look into it yet - sticking it here in case someone knows the answer or so I can pop it in when I find it.  2.3 is fine for me for now, but.. I like to be pretty current.

**Comment by marceloverdijk** [comment]
Hi, I think this is because of: https://github.com/togglz/togglz/issues/190
The console is now available on the management port by default.

It can be disabled by setting `togglz.console.use-management-port: false`

**Comment by markdav** [comment]
Thanks.. that was it alright!

**Comment by marceloverdijk** [comment]
Thx @markdav for confirming!
