### ISSUE TITLE
SystemProperty parameters are defined as large text

### ISSUE THREAD

**Issue by dasniko** [togglz/togglz#208]
During working on #116 I detected, that the `SystemProperty` parameters are defined as _large text_ which results in `textarea` elements in the admin console.
Is this really needed to have a _large text_ for `SystemProperty`?
At least the `name` property doesn't need to be _large_, IMHO.
If this is intendet, just close the issue. Otherwise I can send a PR.

**Comment by chkal** [comment]
Hmmmm. No, I don't see a reason for the textarea either. I'm we should change that. So a PR would be welcome. ;-)

**Comment by chkal** [comment]
Great! Thanks a lot!
