### ISSUE TITLE
Tracking Toggle Usage?

### ISSUE THREAD

**Issue by bobpaige** [togglz/togglz#211]
Is there any built-in way to track (and ideally graph/view in the console) how often certain toggles are used?

For example, I can imagine adding a toggle for a new feature and enabling it on Monday. Then throughout the week track how often that codepath is actually hit. If no one is hitting it, we would roll it back.

If there is some other library (or approach) I could use to achieve the same result, I'm open to suggestions.

**Comment by neocotic** [comment]
Could you maybe just enable logging for Togglz and grep the logs? Alternatively, simply log a message in your own code and grep your own logs.

**Comment by hexmind** [comment]
You can use toglz-slack to usage monitoring: real time notifications or history search.
https://github.com/togglz/togglz/blob/master/slack/README.md

**Comment by bobpaige** [comment]
What about JMX beans, or even just an application-wide counter, that tracks invocations?

The recommended implementation of Togglz is to code your own enum with an "isActive" method. Within that method I could count invocations by name and state (how many times it was true/false). If this is accumulated in JMX, any JMX console could display the results. Alternatively, I could add my own REST endpoint to return the results as JSON.

I'm thinking this is not so hard to add, but it would still be cool if Togglz had this built in. I'm only just starting with Togglz; is there some extension system where I could write a plugin to display these results in the console?

**Comment by bobpaige** [comment]
My workaround was to create a FeatureToggleActivityMonitor class that is constructed for each Toggle (in the enum). Every call to "isActive" on the enum delegates to this monitor class that accumulates the counters I want. 

Bonus that this monitor maintains its own list of all active Toggles so I can return them to our web UI over REST. If Togglz already includes a similar REST endpoint, I'd love to see it, but this will work perfectly for my needs.

**Comment by chkal** [comment]
Thanks for sharing the details about your solution.

I personally don't see much benefit of collecting such metrics to be honest. At least I don't see a use case in my applications for it. But that may be a personal thing.

However, it is great to hear that you were able to integrate such a solution with Togglz
