### ISSUE TITLE
Multiple TogglzConfig classes?

### ISSUE THREAD

**Issue by bobpaige** [togglz/togglz#212]
It is possible to have multiple TogglzConfig classes? I'm thinking not since the docs say we need to provide 1 class that implements that interface, and that class returns the StateRepository and the UserProvider.

My need is this: We build an internal framework with other applications built on top of that. I want to have one set of Feature Toggles for the framework code and allow other teams to add their own Feature Toggles for the product-specific stuff.

Is there a preferred pattern for this, or should I find some way to plug things into my one framework-provided TogglzConfig class?

**Comment by bobpaige** [comment]
Tried it and ran into a couple problems:
1. Feature class must be an enum
I tried making it just a regular class with public static final constants, anticipating that my products could extend this class and use a protected constructor. No dice. Togglz requires it to be an Enum.

2. Multiple TogglzConfig
Next attempt was to create two Feature enums with corresponding TogglzConfig classes. No dice. Can only have one TogglzConfig implementation.

Any other ideas?

**Comment by chkal** [comment]
Please have a closer look at the FeatureManager. It provides several SPIs which provide more fine grained configuration of the FeatureManager. Especially have a look at the FeatureManagerBuilder which provides a fluent interface for configuration.

BTW: I'm thinking about deprecating TogglzConfig in one of the next releases. FeatureManagerProvider is much more powerful.

**Comment by bobpaige** [comment]
But even with the FeatureManager, it appears we are limited to a single Feature class. Am I missing something?

**Comment by chkal** [comment]
Please have a look at the FeatureProvider API. It allows you to provide feature metadata from various sources. And IIRC the enum implementation even supports multiple enums.

**Comment by guidosteinacker1969** [comment]
As the question is answered, I will close this issue
