### ISSUE TITLE
Consider using WebJars for JS/CSS resources

### ISSUE THREAD

**Issue by php-coder** [togglz/togglz#213]
Please, consider using WebJars for static assets. The benefits:
1) applications that already use WebJars won't have 2 copies of the same resources
2) it will become possible to use the same version of Bootstrap/jQuery across the entire application
3) you won't have to hold sources of other projects in the Togglz repository

See for details: http://www.webjars.org/documentation

CC @dasniko

**Comment by chkal** [comment]
Sounds like a good idea. Any other opinions?

**Comment by dasniko** [comment]
yes, we can give it a try.

**Comment by dasniko** [comment]
Just stumbled over this again...
I just had two thoughts on it, and wondering, if it's really a good fit:
* `togglz-console` ist just a JAR file, so, no `webjars` libs would be packed with it. When using it, users must include `webjars` deps themselves, might lead to errors/problems. No out-of-the-box usage would work
* Paths to `webjars` resources would include the version number, e.g. `webjars/bootstrap/3.3.7/css/bootstrap.min.css` - if users already use webjars, but in another version, it won't work. Users would have to use "our" webjars version, which is kind of force I don't like.

Please correct me, if I'm wrong at any of these points and/or how to solve it.

**Comment by php-coder** [comment]
@dasniko Thanks! They're really good points and a food for thoughts.

The first point could be solved by having 2 jars -- one, like we have now, and another `togglz-console-nodeps` that requires user to include some deps on his own).

The second one is more complicated, but looks like https://github.com/webjars/webjars-locator-core could help with it.

**Comment by dasniko** [comment]
@php-coder thanks for pointing me to the `webjars-locator-core`, didn't know this.
I will have a look into it and do some tests. Not yet convinced, especially with having two jars. But, let's see.
Hopefully it won't take another 7 months again ;)

**Comment by php-coder** [comment]
@dasniko Thanks!

If I have to choose between waiting another 7 months and having this feature not implemented, I'd definitely pick the first :)

**Comment by chkal** [comment]
Hey guys. Thanks a lot for continuing the discussion about this. I just posted a few comments on #262.

I know that 7 months are quite some time. But as you may have noticed I don't find much time to work actively on Togglz any more. Therefore any help like such pull requests is highly welcome!

**Comment by chkal** [comment]
Hey all. Unfortunately we had to drop #262 as it was causing some issues. See the comments on #262 for details.

IMHO there are quite some issues with introducing webjars:

* If we use webjars we would basically remove Servlet 2.5 support. Although there are ways to work around this, I'm not sure if it is worth the effort.
* We loose control over the exact version of our CSS/JS dependencies. People using a much newer version of some webjar basically force Togglz to also use this new version. This will lead to problems if newer versions aren't 100% backward compatible (like Bootstrap 4 vs 3)
* I don't see any benefit of using the exact same version of JQuery/Bootstrap for both the console and the webapp itself. Basically the console is an "embedded" webapp. It also doesn't share any CSS with the main app, so why this dependency?

So I'll close this one for now... Sorry about that.
