### ISSUE TITLE
How to enable Features based on Cookies or RequestParameters?

### ISSUE THREAD

**Issue by sivaprasadreddy** [togglz/togglz#214]
I am looking to implement feature toggles based on some cookie value or request parameters. What would be the extension point to hookup the behaviour?  Is providing a Cookie based StateRepository sufficient? 

Any guidance would be helpful. Thanks in advance.

**Comment by neocotic** [comment]
I imagine that you could create a custom `ActivationStrategy` that used `HttpServletRequestHolder` to get the current request. You'd need to depend on `togglz-servlet` and I believe then you just need to use the `TogglzFilter` or add some sort of filter to ensure that `HttpServletRequestHolder` has the correct request (whether using `HttpServletRequestHolderListener` or not).

**Comment by sivaprasadreddy** [comment]
I tried to implement custom **ActivationStrategy** implementation. It seems the **DefaultFeatureManager** considers the Strategy only if the feature is enabled. 

```
public boolean isActive(Feature feature) {

        Validate.notNull(feature, "feature is required");

        FeatureState state = stateRepository.getFeatureState(feature);

        if (state == null) {
            state = getMetaData(feature).getDefaultFeatureState();
        }

        if (state.isEnabled()) {

            // if no strategy is selected, the decision is simple
            String strategyId = state.getStrategyId();
            if (strategyId == null || strategyId.isEmpty()) {
                return true;
            }

            FeatureUser user = userProvider.getCurrentUser();

            // check the selected strategy
            for (ActivationStrategy strategy : strategyProvider.getActivationStrategies()) {
                if (strategy.getId().equalsIgnoreCase(strategyId)) {
                    return strategy.isActive(state, user);
                }
            }
        }

        // if the strategy was not found, the feature should be off
        return false;

    }

```
But there could be scenarios where the feature is disabled by default but i want to enable it based on cookie value. In this case it doesn't work. May be i need to provide custom implementation of **FeatureManager** too?

**Comment by chkal** [comment]
It is correct that activation strategies are only considered if the feature is on. So it works like this:

* If the feature is disabled, the feature is off
* If the feature is enabled and has no activation strategy, the feature is on
* If the feature is enabled ans has an activation strategy, the strategy decides about on vs off.

You should be able to implement your use case with this. You just have to turn on the feature and select your strategy. Everything else (including the fallback behavior) is implemented in the strategy.

**Comment by guidosteinacker1969** [comment]
Seams that the question is answered, so I am closing the issue.
