### ISSUE TITLE
Activation strategy by IP address is not working

### ISSUE THREAD

**Issue by amontenegro** [togglz/togglz#215]
Hey guys, 

There are several things that doesn't work for me:

1) On the admin console, i can't add more than one ip, they are supposed to be separated by comma, however, every time I add more than one, i see this error: "Please enter a valid value for: Client IPs"
2) To get the ip, you get it directly from HttpServletRequest.getRemoteAddr(), however, it could be a good idea if you also check for header X-FORWARDED-FOR, which is how we keep track of the client ip.

Could you please consider fixing those two items? they shouldn't be that much coding

Thanks

**Comment by chkal** [comment]
Thanks for reporting this. The first issue seems to be a bug introduced by a previous contribution. And the second one a definitely a great idea and we should add support for that.

I currently don't find much time to work on Togglz. But pull requests are welcome.

**Comment by amontenegro** [comment]
Hey @chkal,

Could you please give me access to push a new branch in your repo? I just did fixed the errors I found, but cant push my changes:

remote: Permission to togglz/togglz.git denied to amontenegro.
fatal: unable to access 'https://github.com/togglz/togglz.git/': The requested URL returned error: 403 

Thanks

**Comment by neocotic** [comment]
@amontenegro, you could always fork this repo and push your branch to your fork. From there you can still open a pull request. That's the standard process.

https://help.github.com/articles/fork-a-repo/

**Comment by error418** [comment]
This issue seems to be fixed by #222

**Comment by chkal** [comment]
Thanks @error418. I agree, both issues should be fixed in the `master` branch. So I'm closing this one. Feel free to reopen if you run into any issues.
