### ISSUE TITLE
Spring Boot integration to auto-configure filter to populate HttpServletRequestHolder  

### ISSUE THREAD

**Issue by taasjord** [togglz/togglz#237]
I am using the Togglz spring-boot-starter and added a custom strategy to check HTTP header parameter for activation (didn't immediately find one out-of-the-box) . But I noticed that HttpServletRequestHolder does not contain any request object, so I rolled my own filter to populate it. But shouldn't auto-configuration do this by default, in either a filter or interceptor, like the vanilla TogglzFilter does? I have not tested but I assume the other default servlet based strategies maybe doesn't work without it either. 

 I found that it registers SpringSecurityUserProvider if spring-security is on the classpath, so I guess username strategy is taken care of, but I think that the ClientIp and ServerName strategies cannot work without it, unless I missed something here.

**Comment by chkal** [comment]
Hey @marceloverdijk, could you share your thoughts on this?

**Comment by resah** [comment]
Hi,
I have the same problem: I wanted to create a Cookie-based AuthenticationStrategy, but I can't retrieve the HttpServletRequest/HttpServletRequestHolder.

@taasjord Could you help me out with an example implementation of your filter/interceptor until this problem is fixed?

Thanks

**Comment by taasjord** [comment]
Hi @resah. 

Here is my servlet filter to populate the HttpServletRequestHolder:
```
    /**
     * Binds the HttpServletRequest to togglz' HttpServletRequestHolder,
     * since the togglz spring boot starter does not seem to do that.
     */
    protected static class HttpServletRequestHolderFilter implements Filter {

        @Override
        public void init(FilterConfig fc) throws ServletException {
        }

        @Override
        public void doFilter(ServletRequest req, ServletResponse res, FilterChain fc) throws IOException, ServletException {
            try {
                HttpServletRequestHolder.bind((HttpServletRequest) req);
                fc.doFilter(req, res);
            } finally {
                HttpServletRequestHolder.release();
            }
        }

        @Override
        public void destroy() {
        }
    }
```

**Comment by chkal** [comment]
So, what's the official way to automatically configure filters in a Spring Boot app? Togglz uses a `web-fragment.xml` file for Servlet containers. I'm surprised that this doesn't work on Spring Boot.

**Comment by marceloverdijk** [comment]
In Boot I would normally use a `FilterRegistrationBean` (see also https://stackoverflow.com/questions/19825946/how-to-add-a-filter-class-in-spring-boot).

Just like we use a `ServletRegistrationBean` in https://github.com/togglz/togglz/blob/master/spring-boot-starter/src/main/java/org/togglz/spring/boot/autoconfigure/TogglzAutoConfiguration.java.

**Comment by taasjord** [comment]
Alternatively, the bind/release could be implemented as a `HandlerInterceptor`.

**Comment by chkal** [comment]
After reading the SO post, I think that `FilterRegistrationBean` looks like the way to go. It would be awesome if anyone could create a PR for that.

**Comment by resah** [comment]
Thx @taasjord .

I wanted to let you know, that this doesn't seemed to be an issue anymore. My Theory why:

I created an ActivationStrategy, which check for a specific cookie. The FeatureToggle itself was used in a ConstraintValidator and the Constraint was used as a method annotation in a REST controller.
This didn't work at all: I could not retrieve the original request and therefore not check the cookies.

I now removed the FeatureToggle from the ConstraintValidator. Instead the FeatureToggles are only used *inside* a REST controller, where the actual request is already available.

Though it would be  great to have the request already inside the ConstraintValidator ... it didn't seem to be possible.

**Comment by chkal** [comment]
Maybe this is just an issue of filter ordering? If the Togglz filter runs AFTER the corresponding Spring code, you would run into such issues.

**Comment by taasjord** [comment]
I think the TogglzFilter is not loaded when using togglz-spring-boot-starter.

**Comment by chkal** [comment]
It would be great if anyone familiar with Spring Boot could provide a pull request for that. After reading the issue comments again, it looks like a `FilterRegistrationBean` is the way to go.

**Comment by taasjord** [comment]
Adding a `FilterRegistrationBean` is easy. But after reading the source code of TogglzFilter and TogglzAutoConfiguration for spring-boot, I think it is more a question what should go into that filter and how it should be done. 

As I understand it, TogglzFilter does multiple things:
* Configures from the servlet context.
* Bootstraps a `FeatureManager`
* Notifies `FeatureManagerListener`s (start/stop events)
* Notifies `RequestListener`s (request begin/end events), where one of them is `HttpServletRequestHolderListener`, via a composite listener loaded with `Services.getSorted(...)`.

The `TogglzAutoConfiguration` in Spring Boot starter configures from typical spring boot properties, but also creates a `FeatureManager` (but does not notify anyone it seems).

So this is where it gets a bit hazy for me; whether the `TogglzAutoConfiguration` overlaps the `TogglzFilter` in some parts, and in general what is the intention that auto-configuration should do and not do. 

I believe a new filter at least should notify all `RequestListener`s and not just for populating HttpServletRequestHolder, as was my original question.

**Comment by chkal** [comment]
Thanks a lot for posting these details. You are absolutely correct. `TogglzFilter` currently does a lot of things. Actually too many things. :laughing: 

The most important thing to understand is that you can choose between two ways of dealing with the creation of the `FeatureManager`.

  1. Let Togglz automatically create the FeatureManager from the filter and handle its lifecycle. Back in 1.x days this was the only mode available. Or actually it was the way that was promoted via the documentation.
  2. Let the DI container of choice (Spring, CDI, Guice, etc) create and configure the FeatureManager and maintain it. Togglz will then just look up the `FeatureManager` via a `FeatureManagerProvider` implementation.

I think that offering (1) was not a very good idea. And actually I would love to get rid of it in Togglz 3.x. The Spring Boot module clearly uses variant (2). Therefore, most of the code in `TogglzFilter` isn't relevant for Spring Boot (because `bootstrap` should evaluate to `false`).

Therefore, it may be OK to simply use the `TogglzFilter` as it is today in the Spring Boot setup. The only important thing to make sure is that the filter should detect that the app is operating in mode (2) and therefore skip bootstrapping its own `FeatureManager`. Togglz tries to auto detect this via `TogglzFilterConfig` but you can also force one of the two modes by setting a servlet context parameter. Is there any way to do this programmatically in Spring Boot?

I know that all of this is a bit weird and too complex. But it has grown over the years. I really would like to clean this up in Togglz 3.x.

**Comment by taasjord** [comment]
Thank you for the explanation. I briefly tried to register the TogglzFilter and at least it starts without errors, but only when setting the servlet context parameter as you mentioned  (or else it will try to bootstrap feature manager and fail). Alas, I haven't had time yet to actually test activation strategies using this.

Here is a code snippet for that. 
```
@Bean
public FilterRegistrationBean togglzFilter() {
    FilterRegistrationBean registrationBean = new FilterRegistrationBean();
    registrationBean.setFilter(new TogglzFilter());
    return registrationBean;
}

@Bean
public ServletContextInitializer servletContextInitializer() {
    return new ServletContextInitializer() {
        @Override
        public void onStartup(ServletContext servletContext) throws ServletException {
            servletContext.setInitParameter("org.togglz.FEATURE_MANAGER_PROVIDED", "true");
        }
    };
}
```
I can try to make a pull request at some point in time, but I need to dig a bit deeper in setting up unit tests etc.

**Comment by chkal** [comment]
@taasjord: Thanks a lot! This looks great! I'm confident that this solution will work. A pull request would be awesome!

**Comment by arashbi** [comment]
I think the springy way of doing it is to register an interceptor:
```
public class FeatureFilterInterceptor implements HandlerInterceptor {


    private final HttpServletRequestHolderListener listener;

    public FeatureFilterInterceptor(HttpServletRequestHolderListener listener) {
        this.listener = listener;
    }



    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        listener.begin(request, response);
        return true;
    }

    @Override
    public void postHandle(HttpServletRequest request, HttpServletResponse response, Object handler, ModelAndView modelAndView) throws Exception {
        listener.end(request,response);
    }

    @Override
    public void afterCompletion(HttpServletRequest request, HttpServletResponse response, Object handler, Exception ex) throws Exception {

    }
}

```
 I tried to make it work, but I cannot build spring-web-integration. It gives me a class not found exception: 
`Caused by: java.lang.ClassNotFoundException: org.springframework.web.servlet.HandlerInterceptor from [Module "deployment.test.war:main" from Service Module Loader]
`
Not really sure why is this happening.

**Comment by chkal** [comment]
Maybe this is caused by the integration tests? You can either skip the tests for now using `-DskipTests` or make sure that there is no other container listening on port `8080` when you run the build.

**Comment by huehnerlady** [comment]
@bennetelli I would argue that #414 did resolve this issue, what do you think?
