### ISSUE TITLE
Console: Inputs need to get sanitized

### ISSUE THREAD

**Issue by error418** [togglz/togglz#238]
Togglz console inputs do not get sanitized. This makes the console vulnerable to XSS attacks.

By injecting a script into a `Username Activation Stategy` (or a similar free-text strategy), a Stored XSS attack can be performed. Malicious JavaScript could be run for every user logging in to the Togglz Console.

## Reproducing Steps
In this example a Stored XSS attack is performed.

### Input
![grafik](https://user-images.githubusercontent.com/7716544/28869130-0e69029a-777c-11e7-8c89-90e53c11629c.png)

```
"><h3>I was injected</h3><script>alert("me too")</script><span class="
```

### Result
![grafik](https://user-images.githubusercontent.com/7716544/28869179-31f8fb70-777c-11e7-8274-51caa20c3884.png)

**Comment by chkal** [comment]
Thanks a lot for reporting this. This should definitely be fixed. I'll try to find some time to do so this weekend.

**Comment by chkal** [comment]
I just pushed a fix for this. Strategy parameter values are now escaped correctly for rendering.

**Comment by php-coder** [comment]
This is a security issue and I'm surprised that it isn't mentioned in the "what's new" doc.

**Comment by chkal** [comment]
I started to simply link to the list of fixed GitHub issues in the What's new section of the site. The corresponding issue list should include this ticket. Although it may be true that it deserves some special accentuation.
