### ISSUE TITLE
Would be nice if we can have a StateRepository implementation that works with Spring Cloud Config 

### ISSUE THREAD

**Issue by tzoght** [togglz/togglz#239]
I was hoping to find an implementation of StateRepository that uses Spring Cloud Config as a source, but I could not find one. Maybe it exists, and I am not searching in the right place.

I am open to developing one and contributing it to your project, if none exists

**Comment by chkal** [comment]
I don't think there is such a repository. Any contribution is welcome! :-)

**Comment by indraneelb1903** [comment]
@tzoght  Could u elaborate on what exactly you had in mind . I am confused because Spring Cloud Config can have properties present in files , relational database , vault , git and vault. Were u planning to handle all these property sources?

**Comment by guidosteinacker1969** [comment]
As the requirement is unclear, I am closing this issue.

**Comment by tzoght** [comment]
Sorry for the delay on this, I have implemented something like this and will push it when I get the chance
