### ISSUE TITLE
TogglzFilter.java : ability to disable bootstrapping at all ?

### ISSUE THREAD

**Issue by laurentperez** [togglz/togglz#243]
Hi

I have a jar with an implementation of TogglzConfig, under webapp1. Thru transitive maven dependency resolution, this jar ends up under webapp2, webapp2 does not need togglz. I do not use EARs, just plain wars.

My problem : webapp2 fails to deploy, throwing the "or register the implementation in your web.xml as described in the 'Configuration' chapter of the documentation" IllegalStateException. Indeed, webapp2 does not use togglz, so no implementation is defined in its web.xml

In TogglzFilter I could set config.isPerformBootstrap() to return false using org.togglz.FEATURE_MANAGER_PROVIDED, but to do so I need to edit webapp2 web.xml (and every webapp bundling my webapp1 jar).

Is there a proper way to solve this case ?

**Comment by chkal** [comment]
Well, if togglz-servlet is on your classpath, the TogglzFilter will be automatically registered and will also try to bootstrap itself (if not disabled via FEATURE_MANAGER_PROVIDED).

What I don't understand is why togglz ends up in your application classpath although you say that the app doesn't need it.

**Comment by error418** [comment]
I would also suggest to overthink your dependency management. Unused dependencies should not be delivered with your application (also, a dependency to an other webapp sounds kind of weird). You could use [Dependency Exclusions](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) to work around this issue, but this would not be a clean solution in my opinion.

**Comment by laurentperez** [comment]
@error418 agreed, I want to avoid exclusions in the pom.xml. webapps don't depend on each other per se, see below v

@chkal webapp1 has a dependency on jar1, jar1 has classes, and is using togglz, implementation of TogglzConfig is defined in webapp1 web.xml. jar1 has its own lifecycle, it's a component shared along webapps.
then, webapp2 has a dependency on jar1 too, it requires several jar1 classes, but webapp2 has no need/interest for togglz. basically webapp1 has features, webapp2 does not. webapp2 is guaranteed to never call jar1 methods which would use togglz.

but currently, I have to edit webapp2 web.xml either to define the TogglzConfig implementation or passing FEATURE_MANAGER_PROVIDED to the bootstrapper.

I could shade jar1 into a jar1-without-togglz and strip off its togglz dependencies, and let webapp2 use jar1-without-togglz but it's not clean.

Hope it's more clear. Basically I'm looking for a way to disable bootstrap without touching web.xmls. Overriding the bootstrapping class to disable the automation is acceptable (classes are not final), but I don't know if it's the best way.

**Comment by chkal** [comment]
Wouldn't it make sense to declare Togglz as an "optional" dependency in jar1 in this case? In this scenario webapp1 would have to add Togglz to the dependencies and configure it accordingly. And as Togglz is an optional dependency, other webapps wouldn't have to do anything and Togglz won't end up on their classpath.

**Comment by laurentperez** [comment]
@chkal optional is what I was looking for, indeed. ty.
