### ISSUE TITLE
Support for MicroProfile Config

### ISSUE THREAD

**Issue by johnament** [togglz/togglz#250]
Togglz already has support for other property based invocations.  I'd like to propose introducing a MicroProfile Config module.  I'd be happy to even provide the PR, but one question.

MP requires Java 8.  I see that Togglz builds with OpenJDK 7 and Oracle JDK 8.  Is it possible to skip a module if Java version < 8 presently?

**Comment by chkal** [comment]
I like the idea. And a PR would be highly welcome.

However, the JDK version will be an issue. You could set a different target version of the new module, but Travis will still try to build the whole project with JDK7. Not sure how we can solve this.

**Comment by johnament** [comment]
I believe we have can profiles activated based on java version.  I'll make sure I test that out before raising a PR.  You already have a build against Java 8 so it shouldn't cause many problems.

**Comment by chkal** [comment]
Hey @johnament. I think using a Maven property for the target JDK version and overwriting it in the new module should work fine. However, I agree that we will have to exclude this module if the build runs with JDK7. 

To be honest, now as JDK9 has been released, I'm thinking about simply disabling the JDK7 build on Travis. In this  case using the property for the target JDK should be enough. However, the build could still target JDK7 for all modules except for the microprofile one. We just don't run the CI build with JDK7 any more.

Thoughts?

**Comment by chkal** [comment]
Yeah, I think we can close this now!
