### ISSUE TITLE
FeatureManager not found with hierahical contexts

### ISSUE THREAD

**Issue by jkubrynski** [togglz/togglz#251]
With Togglz 2.4.1 and Spring Boot 1.5 sometimes there was an exception "Could not find the FeatureManager.". I realized it's happening because Togglz listens to the `ContextRefreshedEvent`. If you set `management.port` to the different one than `server.port`, Spring creates separate context just for management. If this context is refreshed after the application context it's overriding the binding.

The generic solution is to scan not only the base context but also to include parents.

**Comment by chkal** [comment]
Thanks a lot for the analysis. I totally agree that Togglz should also consider parent contexts. Thanks for providing the pull request! :beers:
