### ISSUE TITLE
Align SystemPropertyActivationStrategy with AbstractPropertyDrivenActivationStrategy

### ISSUE THREAD

**Issue by johnament** [togglz/togglz#254]
Togglz had a pre-existing `SystemPropertyActivationStrategy` which handled reading system properties.  A new base class `AbstractPropertyDrivenActivationStrategy` was added for property based toggles, however this class wasn't changed in the System Property one.

There's two key differences (one positive on each side):

- `SystemPropertyActivationStrategy` allows you to define the value to compare to.  `AbstractPropertyDrivenActivationStrategy` is hard coded to `true`.  It would be good if both supported custom property value comparisons.
- `AbstractPropertyDrivenActivationStrategy` supports automatic property naming, e.g. `togglz.FEATURE_NAME` when the property name isn't specified.  It would be good if `SystemPropertyActivationStrategy` supported this as well.

It seems to me the logical path would be to move value customization into the parent class and make system property extend from that class, this way they get the same feature set.

**Comment by chkal** [comment]
Yeah, I absolutely agree. This totally makes sense. We should do this!

**Comment by johnament** [comment]
@chkal psst, this is missing the 2.5.0 milestone.

**Comment by chkal** [comment]
Ups. Fixed. ;-)
