### ISSUE TITLE
FeatureProvider implementations should not allow its clients to change the default FeatureState in their internal metaDataCache

### ISSUE THREAD

**Issue by GrahamLea** [togglz/togglz#269]
If the first time a FeatureState is retrieved from the FeatureManager.getFeatureState() that FeatureState object is used to change the state (FeatureState.setEnabled()), then that call changes the value of the DefaultFeatureState in the internal cache of metadata in EnumBasedFeatureProvider.metaDataCache / PropertyFeatureProvider.metadata.

Implementations of FeatureMetaData should not allow their internal state (defaultFeatureState) to be modified.

**Comment by chkal** [comment]
Thanks! I just merged your PR!
