### ISSUE TITLE
[QUESTION] Why is PropertyFeatureProvider good for distributed environment?

### ISSUE THREAD

**Issue by MALPI** [togglz/togglz#274]
Hi there,

I am starting investigating togglz for one of our applications an stumbled upon `PropertyFeatureProvider` where the docs state:

> Implementation of FeatureProvider that reads all the feature specification from a Properties instance.     This provider is especially useful in distributed environments. 

Probably I miss something, but why exactly is this one good for distributed environments?

**Comment by chkal** [comment]
Not sure who wrote this back then, but I can try to explain. 

If you use a enum for defining your features and you have distributed environment with many components which need to check features, you will have to shared the enum class between components. And such shared code is usually a bad idea. 

At least this is my interpretation of this statement. :-)

**Comment by MALPI** [comment]
Thanks for clarification. I'd say this definitely depends on what you define as distributed system. Still the usecase of the class is unclear to me.

I'd have the scenario for a redundant setup per service. Where each service would run on it's own ec2 instance. Maybe I even have different versions of the service running. Where I would like to activate certain feature for stack with id a but not for a. Is this possible?
