### ISSUE TITLE
Spring test issue after upgrade to 2.6.0

### ISSUE THREAD

**Issue by amir-khassaia** [togglz/togglz#282]
Hi, Upgrading from 2.5.0.Final to 2.6.0.Final shows up a runtime error with spring tests:
Running on Java 8, Spring 4.3.x

```
java.lang.IncompatibleClassChangeError: Found interface org.springframework.test.context.TestContext, but class was expected

	at org.togglz.spring.test.TogglzTestExecutionListener.beforeTestMethod(TogglzTestExecutionListener.java:30)
	at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:269)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


```

**Comment by chkal** [comment]
Weird, this error is thrown here:

https://github.com/togglz/togglz/blob/2.6.0.Final/spring-core/src/main/java/org/togglz/spring/test/TogglzTestExecutionListener.java#L30

I don't know what is causing this.

**Comment by ruifigueira** [comment]
@amir-khassaia, can you provide a simple test class with the issue so that we can replicate it?

Besides, I found this similar issue: https://github.com/springtestdbunit/spring-test-dbunit/issues/46 , basically in Spring 3.x `TestContext` was a class and now it is an interface., so I suspect the issue is from our side: https://github.com/togglz/togglz/blob/2.6.0.Final/pom.xml#L51

@chkal, I missed that old version of Spring there. I don't think they even support Spring 3.x anymore, we should definitely require at least Spring 4.x.

**Comment by ruifigueira** [comment]
I was checking and Spring 3.x is still supported apparently: https://spring.io/projects/spring-framework#learn, but latest 3.x version is from december 2016: http://repo1.maven.org/maven2/org/springframework/spring-core/3.2.18.RELEASE/

Nevertheless, I think we should only support Spring 4+. Even Spring Boot 1.5 requires Spring 4.2+.

**Comment by chkal** [comment]
I would basically be fine with updating to Spring 4. However, I'm a bit surprised that such a change breaks binary compatibility.

**Comment by amir-khassaia** [comment]
@ruifigueira Haven't got a simple test case handy unfortunately. If I get one going will share.
I also wanted to reiterate this project is using Spring 4.3.18, is this a dependency issue due to changes between 2.5.x and 2.6.x, this works just fine in 2.5.0 for me

**Comment by chkal** [comment]
To be honest, I still don't understand why 2.5.0 works and 2.6.0 not. We didn't change the Spring version between these versions. The only change which **could** cause this is that we now compile with Java 8.

**Comment by amir-khassaia** [comment]
Yep what you said makes sense... I will see if I can poke around some more to find another angle...

**Comment by chkal** [comment]
Don't get me wrong. We will definitely update our dependency on Spring to 4.x (see #283). I'm just really confused why this issue doesn't occur with 2.5.0.Final.

**Comment by ruifigueira** [comment]
Ok, I figured out why this stopped working in 2.6... I changed the `TogglzTestExecutionListener` class from `spring-boot-starter` into `spring-core`, and while `spring-core` uses Spring 3 to compile, `spring-boot-starter` uses the version that Spring Boot declares, which is Spring 4.

**Comment by chkal** [comment]
Oh, yes! That makes sense. I didn't remember that you moved that file.

**Comment by chkal** [comment]
I think in this case we could simply apply #283, backport it to a 2.6.x maintenance branch and release 2.6.1 soon...

**Comment by amir-khassaia** [comment]
Ok great news, thanks for confirming. What would the timeline for 2.6.1 be, couple of weeks type of deal ?

**Comment by chkal** [comment]
I think we should wait for ~2 weeks to see if anything else comes up which we should include in 2.6.1.

**Comment by christianfinckler1212** [comment]
Hello, I am urgently waiting for this bugfix. Would be cool, if you would not wait for too long anymore. Thanks a lot.

**Comment by mr-springtime** [comment]
Likewise 👍 
@ruifigueira Thanks a lot for your hard work on the boot2 upgrade so far!

**Comment by chkal** [comment]
I'll try to find some time in the next days to prepare the maintenance branch for 2.6.x. Stay tuned.

**Comment by joe90p** [comment]
@chkal @ruifigueira thanks for all your work on this, also looking forward for 2.6.1

@christianfinckler1212 @mr-springtime 
If you need a workaround before 2.6.1 is released you can exclude the TogglzTestExecutionListener by running your test with the following Test Runner and using a new Attribute. Example usage also below.

**Test Runner**
```
import org.junit.runners.model.InitializationError;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.context.TestContextManager;
import org.springframework.test.context.TestExecutionListener;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/*
Class that can exclude named TestExecutionListeners.
This Runner exists to get round the issue described here: https://github.com/togglz/togglz/issues/282. When this fix has been released (2.6.1 proposed ATOW) this class can removed.
 */
public class TestExecutionListenerExclusionRunner extends SpringJUnit4ClassRunner {

    private static Logger log = LoggerFactory.getLogger(TestExecutionListenerExclusionRunner.class);


    public TestExecutionListenerExclusionRunner(Class<?> clazz) throws InitializationError {
        super(clazz);
    }

    @Override
    protected TestContextManager createTestContextManager(Class<?> clazz) {
        TestContextManager manager = new TestContextManager(clazz);

        if (clazz.isAnnotationPresent(TestExecutionListenerExclude.class)) {

            Annotation annotation = clazz.getAnnotation(TestExecutionListenerExclude.class);
            TestExecutionListenerExclude exclude = (TestExecutionListenerExclude)annotation;
            Class<? extends TestExecutionListener>[] excludedClassList = exclude.value();

            List<TestExecutionListener> listeners = manager.getTestExecutionListeners();
            List<TestExecutionListener> filteredListeners = listeners.stream().
                    filter(l -> !Arrays.stream(excludedClassList).anyMatch(ex -> ex.isInstance(l))).
                    collect(Collectors.toList());

            try {
                Field f = manager.getClass().getDeclaredField("testExecutionListeners");
                f.setAccessible(true);
                f.set(manager, filteredListeners);
            }
            catch(Exception ex)
            {
                log.warn("Could not set testExecutionListeners via reflection", ex);
            }
        }
        return manager;

    }
}
```

**Attribute**
```
import org.springframework.test.context.TestExecutionListener;

import java.lang.annotation.*;

@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
public @interface TestExecutionListenerExclude {

    Class<? extends TestExecutionListener>[] value() default {};

}
```

**Usage**
```
...
@RunWith(TestExecutionListenerExclusionRunner.class)
@TestExecutionListenerExclude({TogglzTestExecutionListener.class})
public class YourTestClass {
...
```

**Comment by chkal** [comment]
Hi all! I just prepared the `2.6.x` maintenance branch from which we can release `2.6.1.Final`. I backported the Spring version update, so I guess it will fix this issue.

Could anyone give this version a try to verify the fix? Unfortunately the snaphots aren't automatically deployed, so you will have to build the version yourself, but that's eary. Something like:

```bash
git clone https://github.com/togglz/togglz.git togglz
cd togglz
git checkout 2.6.x
mvn -DskipTests install
```

After that you should be able to update your Togglz dependency to `2.6.1-SNAPSHOT` and verify the fix.

Thanks a lot!

**Comment by christianfinckler1212** [comment]
Hello @chkal I build your version and it worked. With the snapshot version I do not get the error anymore. Thank you very much.

One more hint. During building your project, I got the following error: Failed to execute goal on project togglz-project: Could not resolve dependencies for project org.togglz:togglz-project:pom:2.6.1-SNAPSHOT: Could not find artifact sun.jdk:jconsole:jar:jdk at specified path /opt/java/jdk10/../lib/jconsole.jar -> [Help 1]

I could help myself by downloading the missing jar and copying to this strange path. Maybe it is helpful for you to know that.

**Comment by mr-springtime** [comment]
I also tried the `2.6.1-SNAPSHOT` with our application. Build (1.8.0_152) went well, the test issue is solved as well.

The only thing I encountered was a duplicate entry in the console for our feature flag, but I heard this has already been reported as an issue.

**Comment by chkal** [comment]
Thanks for confirming the fix. I'll try to find some time this week to prepare the release.

> One more hint. During building your project, I got the following error: Failed to execute goal on project togglz-project: Could not resolve dependencies for project org.togglz:togglz-project:pom:2.6.1-SNAPSHOT: Could not find artifact sun.jdk:jconsole:jar:jdk at specified path /opt/java/jdk10/../lib/jconsole.jar -> [Help 1]

Thanks, I'm aware of this issue. It's actually the Wildfly version pulled in for the integration tests that is causing this.

**Comment by chkal** [comment]
FYI: I just release 2.6.1.Final. The new version should appear in Maven Central in a few hours. Thanks everyone for testing.
