### ISSUE TITLE
Hardcoded spring version in tests

### ISSUE THREAD

**Issue by jpmsilva** [togglz/togglz#284]
In consequence of #280 we found that there is an hardcoded reference to Spring 3.0 in some tests: SpringBasicOperationTest.java, SpringEarlyFeatureUsageTest.java, ManagedFeatureManagerTest.java and FeatureProxyTest.java

This ticket serves to track progress on the fix, for which I will submit a PR soon.

**Comment by jpmsilva** [comment]
Opened PR #285 for this fix.
However, @ruifigueira mentioned that he may want to merge this patch with #283 instead, to aggregate everything related to the Java 8+Spring 4 bump.
PR #285 is a prerequirement for the tests of #280 to pass

**Comment by chkal** [comment]
I just merged #285, so we can close this one!
