### ISSUE TITLE
Use shinkwrap resolver with project's own pom.xml

### ISSUE THREAD

**Issue by jpmsilva** [togglz/togglz#286]
As mentioned by @chkal it would be preferable to support resolving dependencies with whatever versions are defined in the project's pom.xml instead of the very specific SpringVersion support.
This ticket is to track this improvement.

**Comment by jpmsilva** [comment]
Added PR #287 with an enhancement to resolve dependency versions resorting to the project's own pom.xml file.

**Comment by chkal** [comment]
Great! Thanks! See my comments in #287.

BTW: There is no need to create separate issues if you open a pull request. I don't think it brings much benefit if we duplicate all the details between the issue and the pull request. This seems to be a bit redundant. So why not safe some time. ;-)

**Comment by jpmsilva** [comment]
Hi @chkal 
Sorry for the spam, I will do accordingly. Since the PR is ongoing, I'll close this ticket and will track progress on the PR itself.
