### ISSUE TITLE
Java 8 features cause Bundlor to fail the build

### ISSUE THREAD

**Issue by jpmsilva** [togglz/togglz#290]
Now that Togglz has moved the minimum JVM requirement to 8, it is expected that more Java 8 features, such as lambdas, will start being used throughout the code base.
However, the ASM shaded version bundled with the org.eclipse.virgo.bundlor.maven plugin cannot process Java 8 specific metadata, such as lambdas. This completely fails the build with errors such as

`INFO] --- org.eclipse.virgo.bundlor.maven:1.1.2.RELEASE:bundlor (lamba-bundle-manifest) @ lamba ---
java.lang.ArrayIndexOutOfBoundsException: 28712`

 See https://stackoverflow.com/q/31997681 for a similar report.

The Bundlor plugin appears to no longer be maintained, and in the long term this will probably become more of a restriction on development.

It would be great to have some input from past contributors regarding OSGi compliance of the Togglz project.
I have done some tests with bnd-maven-plugin, and was able to generate the OSGi manifests, but I don't really know how to validate if they are correct, so if someone is willing to step up, we can coordinate further.

**Comment by chkal** [comment]
Just a quick note on this. I had some good experiences with the Felix Maven plugin for creating OSGi manifests with a minimal configuration. See:

https://github.com/mvc-spec/ozark/blob/6b579c2f331a2f9d23096e4823902d6ae957c44a/core/pom.xml#L87-L106

**Comment by bennetelli** [comment]
I removed OSGI recently. So I would like to close this issue.
