### ISSUE TITLE
Docs for Togglz endpoint

### ISSUE THREAD

**Issue by getaaron** [togglz/togglz#296]
I am a new Java Sprint Boot / Togglz developer. I think that Togglz has some feature for Spring Boot apps that will enable a `/togglz` endpoint so frontend clients can see which features are enabled. However, I can only find hints about this. For example:

- https://www.togglz.org/documentation/spring-boot-starter.html says:

    >   endpoint: # Only for Spring Boot 1.x (for Spring Boot 2.x see https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html)

    However, the "Production Ready Endpoints" page doesn't mention Togglz.
- https://github.com/togglz/togglz/pull/221 claims there's an existing `GET /togglz` endpoint
- I see classes that seem related, [like `TogglzEndpoint.java`](https://github.com/togglz/togglz/blob/73fe124195d3a265eec43676f0981afa76f20bed/spring-boot/starter/src/main/java/org/togglz/spring/boot/actuate/TogglzEndpoint.java). 

But I don't see any docs about this specific feature or how to set it up.

So my questions are…

- Is the Togglz endpoint still supported?
- If so, can you tell how to enable it?
- Once I get it working, would you like a docs pull request with more explicit setup instructions?

**Comment by chkal** [comment]
@ruifigueira Could you share some details? I guess you know more about that specific feature.

**Comment by ruifigueira** [comment]
Sorry for the delay.

Indeed, both togglz endpoint and console should be available, as long as you include `togglz-console` and `spring-boot-actuator-starter` in your classpath.

If, even with those dependencies, it doesn't provide the endpoint and console, we need to check it further. In that case, can you provide us the report given by the `/actuator/conditions` endpoint, as well as the `/actuator/configprops`?

**Comment by ruifigueira** [comment]
I forgot to mention that, in Spring Boot 2.0, the endpoint is now available under `/actuator`, which is the default Spring Boot prefix for actuator URLs. So, instead of `GET /togglz`, try `GET /actuator/togglz`.

**Comment by bennetelli** [comment]
@getaaron i just added some documentation about the togglz actuator endpoint: https://www.togglz.org/documentation/spring-boot-starter.html

ps: I know the documentation is a bit weird. I will restructure the whole documentation in the next weeks/months.
