### ISSUE TITLE
Write Endpoints for Spring Boot Actuator

### ISSUE THREAD

**Issue by kschlesselmann** [togglz/togglz#308]
Is there a reason the togglz actuator endpoint is read only?

For anyone interested my current workaround looks like
```
@Component
@EndpointWebExtension(endpoint = TogglzEndpoint::class)
class TogglzEndpointExtension(
        private val featureProvider: FeatureProvider,
        private val featureManager: FeatureManager
) {

    @WriteOperation
    fun setFeatureState(@Selector featureName: String, enabled: Boolean): WebEndpointResponse<FeatureState> {
        val feature = featureProvider.features.first { it.name() == featureName }
        val state = FeatureState(feature, enabled)

        featureManager.setFeatureState(state)

        return WebEndpointResponse(state)
    }
}
```
this enables me to something like `http POST :8080/actuator/togglz/SEND_TO_OPAL enabled=true` to flip toggle states.

If there's no reason it is read only you could include my `@WirteOperation` in the current `@Endpoint` and I could just drop my extension :-)

**Comment by ruifigueira** [comment]
@kschlesselmann, togglz actuator can definitely have that write operatin. If you want to contribute with a PR adding that operation `TogglzEndpoint`, I can review it and merge it.

**Comment by kschlesselmann** [comment]
Hi @ruifigueira, I just opened #310. What do you think?

**Comment by kschlesselmann** [comment]
HI @ruifigueira ! Any updates from your side? Currently I'm not sure if you're waiting on something else from me :-P

**Comment by ruifigueira** [comment]
I'm sorry :) I think that ultimately we should go with the `EndpointWebExtension` but it's something we can address in a different MR. For now, I think we should not return `null` in the `@WriteOperation`, because semantically is not very clear. Everything else is perfect.

**Comment by ruifigueira** [comment]
We also should include something in the documentation into https://www.togglz.org/documentation/spring-boot-starter.html.

Maybe something like https://docs.spring.io/spring-boot/docs/current/actuator-api/html/#loggers-setting-level
