### ISSUE TITLE
The status of all features are reset after running test

### ISSUE THREAD

**Issue by lofrank** [togglz/togglz#311]
I use a JDBC state repository.
The issue is all features were disabled (the default status) after running spring boot tests, even the status in DB was modified.
This is a very critical problem, anyone can share some suggestions to investigate this issue?
Thanks

Following two packages were used:
    compile("org.togglz:togglz-spring-boot-starter:2.6.1.Final")
    compile("org.togglz:togglz-console:2.6.1.Final")

Here is my configuration:
`@Component
public class MyTogglzConfig implements TogglzConfig {

    private final DataSource dataSource;

    @Autowired
    public MyTogglzConfig(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public Class<? extends Feature> getFeatureClass() {
        return MyFeatures.class;
    }

    @Bean
    public FeatureProvider featureProvider() {
        return new EnumBasedFeatureProvider(MyFeatures.class);
    }

    @Bean
    public StateRepository getStateRepository() {
        StateRepository t = new JDBCStateRepository(dataSource);
        return t;
    }

    @Bean
    @Override
    public UserProvider getUserProvider() {
        return new UserProvider() {
            @Override
            public FeatureUser getCurrentUser() {
                UserInfoModel userInfoModel = (UserInfoModel)request.getAttribute(ConfigManager.USER_INFO);
                if(userInfoModel != null && !Utils.isNullOrEmpty(userInfoModel.getUserName())) {
                    return new SimpleFeatureUser(userInfoModel.getUserName(), false);
                }
                return null;
            }
        };
    }
}`

**Comment by lofrank** [comment]
Got it, all feature states will be set to default one in TogglzTestExecutionListener.
I'm looking for a way to disable this behavior now.

**Comment by chkal** [comment]
Well, it looks like you are using the JDBC state repository in your tests, which is most likely not what you want to do. There is a special `togglz-junit` module which helps to use Togglz in tests. This will by default use an in-memory state repository for tests. You should have a look at the documentation.

https://www.togglz.org/documentation/testing.html

**Comment by lofrank** [comment]
Thanks chkal
It does not work, even after adding togglz-junit package.

I solve the issue by following code: (use InMemoryStateRepository in test)

@RunWith(SpringRunner.class)
@ContextConfiguration
public abstract class RestApiTest {

    @TestConfiguration
    static class Config {

        // this bean will be injected into the RestApiTest class
        @Bean
        public StateRepository getStateRepository() {
            return new InMemoryStateRepository();
        }
    }
    // tests
}
