### ISSUE TITLE
when will 2.6.2 be released ?

### ISSUE THREAD

**Issue by sagar-jani** [togglz/togglz#322]
we are currently using **Spring-boot 2.8.0** and **togglz 2.6.1-Final** versions and facing the same issue mentioned in  **#312.** we are in urgent need of this fix, is it possible for you to release the next version with this fix ?

**Comment by chkal** [comment]
There are currently no plans for a release. Mostly, because of the reasons outlined [here](https://groups.google.com/forum/#!topic/togglz-dev/-DPU5w_slG8). Maybe I'll find some time in the next weeks to do so. But I cannot provide any guarantee.

**Comment by guidosteinacker1969** [comment]
Hi all,
as Christian has just posted [here](https://groups.google.com/forum/#!topic/togglz-dev/OBQHsJnreEE), we at Otto will help him to maintain the Togglz libraries in the future. The good news is, that the next release 2.7.0 is already in preparation. But: we have just started a few days ago, so we are currently not able to tell you a release date. Personally, I'm optimistic enough to expect the upcoming release  within November 2019.

**Comment by php-coder** [comment]
> we are currently using Spring-boot 2.8.0

By the way there is no such version. The latest available is 2.2.2

**Comment by bennetelli** [comment]
I would like to close this issue because togglz has been released already.
