### ISSUE TITLE
HazelcastStateRepository does not allow for client-server Hazelcast model

### ISSUE THREAD

**Issue by Jeffrey-Hassan** [togglz/togglz#354]
The HazelcastStateRepository takes a Config object only, which is the configuration for Hazelcast server.  The constructors + builders should also allow for using:

* ClientConfig for client-server model and 
* HazelcastInstance when we'd rather build that externally (can be built with either client or server configuration)

Therefore there should be 3 constructors in addition to the builder.  Additionally, builder should throw exception if more than 1 of the 3 (Config, ClientConfig, HazelcastInstance) is configured.

**Comment by bennetelli** [comment]
fixed in PR #355
