### ISSUE TITLE
Togglz Spring Boot Starter and Spring Security not playing nicely together

### ISSUE THREAD

**Issue by bitbythecron** [togglz/togglz#365]
Hi there!

I have an existing Spring Boot (2.2.5) web service (**that currently uses Spring Security for JWT-based auth**) and am trying to give Togglz a try. I added the Togglz/Spring Boot starter:

```
implementation("org.togglz:togglz-spring-boot-starter:2.6.1.Final")
```

and added a new feature enum:

```
public enum FeatureToggle implements Feature {
    @Label(value = "Email Fetching")
    EMAIL_FETCHING

}
```

I then created a new `EnumBasedFeatureProvider` bean:

```
@Configuration
public class TogglzConfig {

    @Bean
    @SuppressWarnings(value = "unchecked")
    public FeatureProvider featureProvider() {
        return new EnumBasedFeatureProvider(FeatureToggle.class);
    }

}
```

And made an adjustment to my `application.yml`:

```
togglz:
  features:
    EMAIL_FETCHING:
      enabled: true
```

When I go to run my Spring Boot app, it fails at startup with the following error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of method featureManager in org.togglz.spring.boot.autoconfigure.TogglzAutoConfiguration$FeatureManagerConfiguration required a bean of type 'org.togglz.core.user.UserProvider' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'userProvider' in 'TogglzAutoConfiguration.SpringSecurityUserProviderConfiguration' not loaded because @ConditionalOnClass did not find required class 'org.togglz.spring.security.SpringSecurityUserProvider'
	- Bean method 'userProvider' in 'TogglzAutoConfiguration.UserProviderConfiguration' not loaded because @ConditionalOnMissingClass found unwanted class 'org.springframework.security.config.annotation.web.configuration.EnableWebSecurity'
```

The only place I use `@EnableWebSecurity` is in my web security configuration class:

```
@EnableWebSecurity
public class WebServiceSecurity extends WebSecurityConfigurerAdapter {
   ...
}
```

**At this time I do not wish to have Togglz to provide _any_ security-related functionality.** So if there's a way to disable anything the Togglz/Spring Boot Starter does w.r.t security, I'd like to do that!

Do I have something misconfigured?

**Comment by tdevilleduc** [comment]
You should have a UserProvider bean
One way to do that is to create it manually


```
    @Bean
    fun userProvider(): UserProvider {
        return NoOpUserProvider()
    }
```

**Comment by bennetelli** [comment]
@bitbythecron did you find a way to fix your issue or do you still need help? Maybe I will find some time to answer your issue this week.
