### ISSUE TITLE
Create file if it doesn't exist - FileBasedStateRepository

### ISSUE THREAD

**Issue by kevinstembridge** [togglz/togglz#366]
When using the FileBasedStateRepository, if the configured file doesn't exist you get a FileNotFoundException the first time you try to edit a toggle.

I think it would be good to have the option to create the file on startup if it doesn't exist.

**Comment by bennetelli** [comment]
Hey,

thanks for your issue. This feature is easily to implement. I will add an additional property you can add to the application.yml / application.properties file to enable the creation of a file if it doesn't exist.

**Comment by beatfreaker** [comment]
@bennetelli can I try to implement this ?
I think we have to add code to create file if not exists in [TogglzAutoConfiguration.java#L168](https://github.com/togglz/togglz/blob/master/spring-boot/starter/src/main/java/org/togglz/spring/boot/actuate/autoconfigure/TogglzAutoConfiguration.java#L168)
Also should we handle exception while creating file if file path is not valid ?

```java
@Bean
public StateRepository stateRepository() throws IOException {
    StateRepository stateRepository;
    String featuresFile = properties.getFeaturesFile();
    if (featuresFile != null) {
        Resource resource = this.resourceLoader.getResource(featuresFile);
        Integer minCheckInterval = properties.getFeaturesFileMinCheckInterval();
        resource.getFile().createNewFile(); // Added to create new file
        if (minCheckInterval != null) {
            stateRepository = new FileBasedStateRepository(resource.getFile(), minCheckInterval);
        } else {
            stateRepository = new FileBasedStateRepository(resource.getFile());
        }
    }
    ....
    ....
    return stateRepository;
}
```

**Comment by bennetelli** [comment]
hey @beatfreaker of course you can. Just add a Pull Request :-)

**Comment by kevinstembridge** [comment]
Nice one.

Thanks guys.

**Comment by bennetelli** [comment]
@kevinstembridge @beatfreaker do you need it ASAP? Or is it okay for you to get the release in the next 2-3 days?

**Comment by kevinstembridge** [comment]
No hurry from me. I did something manually as a workaround. So I'm fine to wait for whenever you do another release.
