### ISSUE TITLE
MongoDB 4 Issue

### ISSUE THREAD

**Issue by KMcL27** [togglz/togglz#372]
I tried updating our project to spring-boot 2.3.0, which now supports mongodb 4.
The togglz code uses a method com.mongodb.client.MongoCollection.replaceOne
with a signature that is no longer supported i.e. 3rd param expects ReplaceOptions
rather than UpdateOptions.

**Comment by bennetelli** [comment]
Working on it. The issue should be related to the MongoDB 3.X dependency we are using in togglz. Think I have to replace it with 4.X-sync or something like that.

**Comment by mickeviciusVytautas** [comment]
When can we expect to see the migration from MongoDB 3.X to 4.X? The artifacts were split in 4.X as you can see here https://docs.spring.io/spring-data/mongodb/docs/3.0.3.RELEASE/reference/html/#upgrading.2-3

**Comment by bennetelli** [comment]
Will fix it this week.

**Comment by bennetelli** [comment]
as promised, the PR: #415
