### ISSUE TITLE
Find a better way to work with the OWASP security plugin

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz#388]
Currently it just takes too long to build the application. IMO we should find a better way to work with it.

**Comment by php-coder** [comment]
How about run it time-to-time in TravisCI? See https://docs.travis-ci.com/user/cron-jobs/

**Comment by bennetelli** [comment]
@php-coder this could be a solution. Whereas I thought about migrating from TravisCI to CI/CD with GitHub Actions.

**Comment by bennetelli** [comment]
see #464

**Comment by bennetelli** [comment]
fixed.
