### ISSUE TITLE
Togglz auto configuration is not working with togglz 2.7.0

### ISSUE THREAD

**Issue by sanintel3** [togglz/togglz#401]
When togglz library is upgraded to 2.7.0 (from 2.6.1.Final) and accessing togglz-console/index is throwing below exception

```java.lang.IllegalStateException: Could not find the FeatureManager. For web applications please verify that the TogglzFilter starts up correctly. In other deployment scenarios you will typically have to implement a FeatureManagerProvider as described in the 'Advanced Configuration' chapter of the documentation.```

It looks like Togglz auto configuration is not triggered and due to this featureManager bean is not available to the application during runtime

spring boot version: 2.3.1

**Comment by bennetschulz1309** [comment]
Hey, thanks for your PR. I just figured it out my self :(
This is kinda strange. I tested it before, but it looks like intelliJ is caching dependencies on his own internally.

I'm working on it.

**Comment by sanintel3** [comment]
Looks like togglz spring boot starter is not bundling spring-boot-auto-configure dependency

**Comment by sanintel3** [comment]
is there any quick work around for this? do you think by adding below dependency explicitly will resolve it or may cause side effects due to version conflict?

```implementation("org.togglz:togglz-spring-boot-auto-configure:2.6.1.Final")```

**Comment by bennetelli** [comment]
Thanks for the hint. Actually I don't know why this additional Auto Configuration is necessary in the spring.factories file. It wasn't the version before.

**Comment by bennetelli** [comment]
@sanintel3 Just added a PR (#403) which updates the spring boot dependency and adds your entry to the spring.factories file.
Will release togglz 2.7.1 on saturday or monday.
After that I will try to find a better solution for this strange scenario.

**Comment by sanintel3** [comment]
Thanks @bennetelli @bennetschulz1309 for quick response

**Comment by bennetelli** [comment]
@sanintel3 I just released 2.7.1. My togglz-sample setup works as expected. I think you can remove your work around and update to 2.7.1.
Thanks again for opening this issue and helping with it :)

**Comment by sanintel3** [comment]
Thanks for the quick fix, much appreciated
