### ISSUE TITLE
Enable Spring Boot togglz endpoint by default

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz#402]
currenty we have to use this property entry to enable all existing endpoints:
management.endpoints.web.exposure.include=*

it would be better to enable the togglz endpoint, only.

Without adding this property, the togglz endpoint wouldn't be exposed as an actuator endpoint.

**Comment by gavarava** [comment]
What happened to this issue ? Was it fixed or decided to not do ? @bennetelli

**Comment by bennetelli** [comment]
Hey @gavarava you still have to add the management.endpoints.web.exposure.include=* (or even the exact endpoint) to let Spring Boot / actuator know that this endpoint should be exposed. 
I didn't find any good documentation of how to enable it by default. If you have something, please let me know :) Maybe you even want to provide a PR which fixes it? :)

**Comment by gavarava** [comment]
Didn't get far. Went for our own handcrafted API endpoints to update without the Actuator, since all we needed was to update it from a different UI client.
