### ISSUE TITLE
Various 404 not found errors using togglz console

### ISSUE THREAD

**Issue by smcgregor83** [togglz/togglz#404]
Firstly, great to see a new release of this project. I'm very happy to see that the project has a new home.

I've noticed a small issue whilst doing an upgrade. This doesn't seem to have any functional impact, but does cause some styling issues on the console.

The following resources are returning a 404:

- /fonts/glyphicons-halflings-regular.ttf
- /fonts/glyphicons-halflings-regular.woff
- /fonts/glyphicons-halflings-regular.woff2
- /togglz-console/jquery-min.js

I did a little debugging and I think that the regex in org.togglz.console.handlers.ResourceHandler needs updated to handle *-min.js and the fonts directory.

**Comment by bennetelli** [comment]
Hey @smcgregor83 thanks for your issue :-) 
Argh.. I just released version 2.7.1. Looks like I have to create another patch release as well.. Will fix it asap.

**Comment by smcgregor83** [comment]
Thanks @bennetelli much appreciated.

**Comment by bennetelli** [comment]
hey @smcgregor83 i just fixed the errors and all the other warnings and so on. (see #406)
