### ISSUE TITLE
Add default ActivationStrategy based on header

### ISSUE THREAD

**Issue by huehnerlady** [togglz/togglz#412]
Hi,

I was kind of expecting to have a DefaultActivationStrategy for a predefined header that will be processed in the scope of spring-boot with a servlet configuration, similar to eg. the [QueryParameterActivationStrategy](https://github.com/togglz/togglz/blob/master/servlet/src/main/java/org/togglz/servlet/activation/QueryParameterActivationStrategy.java). I saw in #237 that someone else created a custom Strategy for this, so I guess for now I might have to do the same

Is there any plan to implement a header based activation stragtegy?

**Comment by bennetelli** [comment]
Hey,

actually there was no need to implement something like this in the past. Will take a look at it and add this activation strategy to the project as soon as possible so you don't have to use your custom one for a long time.

**Comment by huehnerlady** [comment]
@bennetelli many thanks for the answer.
I am very happy to hear that, many thanks.

**Comment by huehnerlady** [comment]
I did not know that togglz does not work with kotlin so I can cancel this issue as it is no longer needed for me

**Comment by huehnerlady** [comment]
@bennetelli I did implement it locally now and I thought I would contribute (see related PR). If this is not wanted please say so and I will remove the Pull Request again.

**Comment by bennetelli** [comment]
Of course it is :) 
Would love to get your pull request :)
