### ISSUE TITLE
Spring Boot Actuator "togglz" endpoint not exposed

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz#429]

**Comment by deen13** [comment]
I ran into this issue also while setting up togglz in our kotlin project. For some reason the actuator endpoint is exposed if I convert the `com.ctrace.wallboard.togglz.TogglzEndpointAutoConfiguration` into a kotlin class.

**Comment by bennetelli** [comment]
@deen13 thanks for your response. I remember working on it some months ago. Will take a look at it.

**Comment by alfonz19** [comment]
there seems to be duplicate key in 2.8.0/togglz-spring-boot-starter-2.8.0.jar!/META-INF/spring.factories

**Comment by fabianlinz** [comment]
This should be fixed with 2.9.0

**Comment by bennetelli** [comment]
@fabianlinz thanks for the hint. Indeed. It's fixed already. So I would like to close this issue.
