### ISSUE TITLE
Replace com.netflix.astyanax with DataStax Java Driver for Cassandra

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz#437]
https://github.com/datastax/java-driver

**Comment by hennr** [comment]
The cassandra support is badly outdated and does not even work under java 11+ (probably not even on 9ü+) I would say.

Are there really any users left? If not you could just drop this module @bennetelli

**Comment by hennr** [comment]
Update: Maybe only the tests are broken for the cassandra support in Java 11, I don't really know yet.

**Comment by bennetelli** [comment]
we don't know about the users. I tried it several times but only got a response after just deleting modules.. :-D
