### ISSUE TITLE
Remove java Scripting API Activation Strategy

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz#448]

**Comment by bennetelli** [comment]
see #451

**Comment by mattluce** [comment]
Curious why this was removed?

**Comment by bennetelli** [comment]
Hey, actually it was because of security issues. I thought this feature wouldn't be that popular so I deleted it. 
I raised an issue containing a question if someone needs this activation strategy.

I can add it again if you need it. Will build a release tomorrow which contains the scripting activation strategy.

**Comment by mattluce** [comment]
Thx. We definitely use it.

**Comment by mattluce** [comment]
With nashorn being deprecated, this may not make sense any longer. Do you have the original issue with security issues listed?

**Comment by bennetelli** [comment]
I could try to implement it with Rhino so it can be used with Java > 11 as well.

Actually it's pretty hard to get feedback from the community. I raised an issue and asked if someone is using the scripting api.
Looks like I will have to keep supporting different features and frameworks even if nobody replies to my issues. Thanks for the hint. Will add it again.

**Comment by bennetelli** [comment]
just added the scripting api again. see #523

**Comment by bennetelli** [comment]
Hey @mattluce It's part of release 2.9.6 again. Please take a look at it and give me feedback if its working for you. best regards, Bennet

**Comment by mattluce** [comment]
There seems to be an issue with escaping of quotes. See image:
![image](https://user-images.githubusercontent.com/1022559/111521679-67ce9c00-8727-11eb-86f8-e79e857238b1.png)
