### ISSUE TITLE
Update arquillian to 1.7.0.Alpha and update to JUnit 5 in every project

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz#458]

**Comment by hennr** [comment]
Does this also mean you are good to convert spock tests (e.g. in togglz-slack, see #467) to JUnit 5 tests?
I guess it would be a good idea to handle the maintenance load better.

**Comment by bennetelli** [comment]
I am currently doing this, yes. I do have the PR on my machine. I only need to fix two tests. The rest is already working with junit instead of groovy.

**Comment by bennetelli** [comment]
here's the PR #659

**Comment by bennetelli** [comment]
btw. do you have an idea of how to deal with Arquillian? @hennr 

I would like to remove it completely as it's old fashioned stuff and I don't like the api that much tbh. 
I thought about using Quarkus for it, but I am not sure if that's the way to go. Maybe it's not, but I don't know a better solution for it. What are your thoughts?

**Comment by hennr** [comment]
> here's the PR #659

That's awesome!
I just send a PR #665 to make these new junit 4 tests junit 5 tests :)

**Comment by hennr** [comment]
> btw. do you have an idea of how to deal with Arquillian? @hennr
> 
> I would like to remove it completely as it's old fashioned stuff and I don't like the api that much tbh. I thought about using Quarkus for it, but I am not sure if that's the way to go. Maybe it's not, but I don't know a better solution for it. What are your thoughts?

It's been ages since I touched arquillian, and I cannot really help with the move to 1.7.0 as such. Also I had no touch points with Quarkus so far, but if it's more promising than maintenance state of arquillian I would go for it.
I cannot say if it's sufficient though, sorry.
