### ISSUE TITLE
io.kotlintest:kotlintest-runner-junit5 dependency should have test scope in the kotlin module

### ISSUE THREAD

**Issue by kevinstembridge** [togglz/togglz#459]
I think the following ...

    <dependency>
      <groupId>io.kotlintest</groupId>
      <artifactId>kotlintest-runner-junit5</artifactId>
      <version>3.4.2</version>
    </dependency>

... in...

https://github.com/togglz/togglz/blob/master/kotlin/pom.xml

... was probably intended to be marked as test scope.

**Comment by bennetelli** [comment]
thanks for adding this issue. Fixed it in #463

**Comment by kevinstembridge** [comment]
Thanks
One of my finest contributions :)

**Comment by bennetelli** [comment]
And one of my dumbest mistakes ;)
