### ISSUE TITLE
Test dependencies have wrong scope

### ISSUE THREAD

**Issue by aburmeis** [togglz/togglz#460]
Currently and for a while some test dependencies starting at `togglz-core` have the wrong scope in `pom.xml`, missing `<scope>test</scope>`. Therefore using togglz in your project ether result in production dependencies like Mockito or requires explicit excludes on groups like `org.mockito`or `junit`.

Examples: `togglz-core`, `togglz-spring-core`, `togglz-spring-security`

Seen on master/2.8.0

**Comment by bennetelli** [comment]
Hey @aburmeis , thanks for opening this issue. I just fixed all the test dependencies I found so far in PR:  #461

**Comment by aburmeis** [comment]
Thank you Bennet! Seems fine from my side, looking forward to the next Release. Greetings from Berlin to Hamburg 👋

**Comment by bennetelli** [comment]
I will build and release a patch now, so you can update to a togglz version without these dependencies issues. 

Greetings back to Berlin :-) Have a nice day :)

**Comment by bennetelli** [comment]
aah btw @aburmeis let me know if you need an additional feature or some changes in togglz :)
