### ISSUE TITLE
@Selector of TogglzEndpoint is not bound by path variable

### ISSUE THREAD

**Issue by kschlesselmann** [togglz/togglz#470]
I've created a little showcase at https://github.com/kschlesselmann/togglz-demo which shows that the `@Selector` of the togglz endpoint is not properly read from the URL but is required to trigger the endpoint nevertheless.

https://github.com/kschlesselmann/togglz-demo/blob/main/src/test/kotlin/com/example/demo/DemoApplicationTests.kt#L29 tries to use the actual desired behavior which fails with 400 Bad Request. I've put a custom endpoint next to it to show that it should work.

Do you have an idea what's special about the endpoint provided by the togglz starter?

**Comment by bennetelli** [comment]
see: https://stackoverflow.com/questions/47920201/how-do-you-use-selector-in-writeoperation-in-spring-boot-2-0-actuator-endp

**Comment by bennetelli** [comment]
@kschlesselmann it's fixed now. Will build a new release on monday so you can use togglz actuator endpoints as expected in 2.9.3.
