### ISSUE TITLE
'mvn test' does not execute any testes of togglz-spring-web'

### ISSUE THREAD

**Issue by m-schroeer** [togglz/togglz#497]
I noticed (locally and on [travis (builds/754281231)](https://travis-ci.org/github/togglz/togglz/builds/754281231)) that maven tests of [togglz-spring-web](https://github.com/togglz/togglz/tree/master/spring-web) (`mvn test`) are not executed (see image below).

<img width="655" alt="image" src="https://user-images.githubusercontent.com/16744580/104471646-6532b780-55bb-11eb-839a-cbb5cd3f47da.png">.

By now I had no time to investigate this by myself. Maybe someone has an idea about it.

**Comment by bennetelli** [comment]
yes, I have it on my list already. We had the same sh** in some other projects as well. Took some time to fix it in the other projects and togglz-web is still the last open one.

**Comment by bennetelli** [comment]
It's working now. Fixed it in #506.
