### ISSUE TITLE
CSRF token validation fails if Togglz is run on multiple instances behind a loadbalancer

### ISSUE THREAD

**Issue by christopherkeil0689** [togglz/togglz#500]
The new CSRF token validation implemented for version 2.9.4 in [this commit ](https://github.com/togglz/togglz/commit/ed66e3f584de954297ebaf98ea4a235286784707) fails if Togglz is run within an application that is replicated across multiple instances behind a loadbalancer.

The token is generated, for example upon rendering a page, and is then put into a _local cache_ on the instance which generated the token. It is then shared with the browser so it can be used as a query parameter for subsequent requests against Togglz endpoints (e.g. `/some/togglz/endpoint&togglz_csrf=blablabla-yadada-lalala`).

On a single instance, this is fine because the instance which generated, saved and shared the token will be the same to receive any request later on. However, behind a loadbalancer this is not the case. Once two instances or more are running it is a gamble whether the instance who receives the token is the same which put into its own cache in the first place. `n-1` instances will not know the token and have no way to validate it.

Since CSRF validation cannot be turned off using a property/configuration, Togglz is currently broken for the use case of managing a load-balanced application.

**Comment by bennetelli** [comment]
@christopherkeil0689 i just released togglz 2.9.5 which contains your fix.
You can disable the CSRF validation by setting the togglz.validateCSRFToken = false
entry in your application.yml/properties.
