### ISSUE TITLE
togglz-junit isn't being published anymore

### ISSUE THREAD

**Issue by leonard84** [togglz/togglz#521]
The last commit available in central https://search.maven.org/search?q=togglz-junit is 2.9.2, while currently 2.9.5 is released.

**Comment by bennetelli** [comment]
Yes, that's true. I migrated togglz-junit from junit4 to junit 5 some time ago. 
Do you still need the togglz-junit4 support? :-/

**Comment by leonard84** [comment]
> Do you still need the togglz-junit4 support? :-/

Yes, as I already mentioned in #432, but the issue here is that `togglz-core` is at 2.9.5 `togglz-junit` is at 2.9.2 so the rename seems to also have messed with the publishing.

**Comment by bennetelli** [comment]
hey @leonard84 it's published in version 2.9.6 I released some ours ago. Would be great if you could give me some feedback if it's working for you. best regards,
Bennet

**Comment by leonard84** [comment]
Looks good and junit 4 support seems to work as well, thanks @bennetelli

**Comment by bennetelli** [comment]
@leonard84 you're welcome :) thanks for adding the issue and also thanks for the discussion :)
