### ISSUE TITLE
Update release notes

### ISSUE THREAD

**Issue by leonard84** [togglz/togglz#522]
There are no release notes after 2.6 on any of these locations, making it rather hard to figure out what has changed and has to be done. For example that junit4 support seems to have been dropped, in some version.

* https://www.togglz.org/
* https://www.togglz.org/updating-notes.html
* https://github.com/togglz/togglz/releases

**Comment by bennetelli** [comment]
Hey @leonard84 okay, looks like you take a look at the website. So I will add the Update/Release Notes to togglz.org as well.
Nevertheless, I started adding bullet points to: https://github.com/togglz/togglz/releases

Will work on it.

**Comment by leonard84** [comment]
IMHO you can maintain it at one location and simply point to it from the other.

**Comment by drekbour** [comment]
IMO togglz.org website should be the "shop front": devoted to what togglz does and how to use it. Github will do the rest for you for you.

**Comment by bennetelli** [comment]
yea, that's probably the best way. I will migrate it to togglz.org then.

**Comment by drekbour** [comment]
I was actually hinting at the other way :) 2021 doesn't need custom sites hosting Javadoc, binaries and RSS feeds.

Release notes/history go into Git (See `CHANGELOG.md`). Also see https://github.com/release-notes for tooling that tries to automate these from your Git sources - I generally find these tools "help" to collect together a draft but, given commits come from community not a core team, I could never control the content sufficiently to automate.

Github Releases is for _applications_. Togglz is a library - no one gets its compiled form Github (hint - the version there is 5 years old!). I recommend purging the Release section and disabling it in your project settings.

The website front page should advertise this cool product. This may include announcements on _headline_ release items when those occur but generally just point to github ("For sources and contributions"), github CHANGELOG.md ("For full release details") and mvnrepository ("For build dependencies"), stackoverflow/gitter ("For usage questions"). We're all devs and know how to use this stuff so long as we have the key links.
Advertising could also highlight the many technical integrations (I was surprised at how popular this library is via the number of community subbed repositories).
Don't be shy to put a patreon etc link in there too for anyone wants to buy you a beer.

The rest of the site should (very much my opinion) be howto's/recipes showing how best to _use_ the many features (e.g. I still get confused about activation-strategies vs state-repositories)

**Comment by bennetelli** [comment]
Much thanks for your response :) 

I do like the custom site in general. The design is a bit oldfashioned and a lof of stuff there is not needed in my opinion as well. 

What do you mean with GitHub releases? Probably not this one here: https://github.com/togglz/togglz/releases ?

Thanks for the hint regarding the activation-strategies vs state repos. Will take a look at it.

I do need to get rid of some stuff and make it more maintainable. It's actually very hard to maintain the library and all that stuff around it in my free time.

**Comment by drekbour** [comment]
My gut feel is that simple existence of a custom site immediately makes the library feel more polished :)

> hat do you mean with GitHub releases? Probably not this one here: https://github.com/togglz/togglz/releases ?
I did actually. If it's "free" then ok, but I would not myself expend _any_ effort on that page for a library. Just have a `CHANGELOG.md`. The content of your repo is your asset not the wraparound stuff Github is adding :)

Also (just exposing personal preferences here!) I dislike github Wiki (that's another area you should purge IMO).

> t's actually very hard to maintain the library and all that stuff around it in my free time.
Make the site content a versioned asset so others can contribute. Tools like hugo and adoc let you build static sites from versioned sources you can host those or, if tech doesn't allow that Github Pages will happily host a git-versioned, CI-built, docker-contained site. You'd have a https://togglz.github.io site and, if you wish to keep it, the public URL can just redirect here. Many options exist here and I'm no expert in this area.

Last thought. Diagrams! Maybe it's just me but there's a lot of text and I'm a visual learner - a well thought out diagram is indeed worth a 1000 words. I'd help if there was a site I could PR to :)

**Comment by leonard84** [comment]
> Github Releases is for _applications_. Togglz is a library

I don't see a reason not to use it for libraries as well, many libraries use it, e.g., https://github.com/junit-team/junit5/releases

**Comment by drekbour** [comment]
Fair enough, they also have a static site hosted with Github Pages. A reasonable path for a small library would be simply to follow their lead :)

**Comment by hennr** [comment]
> I do need to get rid of some stuff and make it more maintainable. It's actually very hard to maintain the library and all that stuff around it in my free time.

What do you have in mind to get rid of?
Where could you use some help to increase the maintainability?

**Comment by bennetelli** [comment]
Guice, Deltaspike and Shiro for example. I am also working on a Quarkus extension similar to the Spring Boot starter.

**Comment by hennr** [comment]
Fine with me, as we don't use any of these ;)

I communication channel with the users would be nice, I guess. Some place to say: If nobody steps up for maintenance, xyz will be dropped in the next release.

**Comment by bennetelli** [comment]
I did that already, but usually people start responding after things have changed. 99% of the togglz users is just updating the dependency and not reading docs, issues or stuff like that.

I will just remove it and see what happens.

**Comment by borisklug** [comment]
The last news on https://www.togglz.org/ are still from October 2019. This still confuses new users but also old users like me.

Maybe just remove the news and all version related stuff on the site and redirect the users to github.

I also want to say thank you for this great piece of software. At my work - a big insurance company - we use Togglz in an big inhouse application for a lot of things. It works perfect.

**Comment by bennetelli** [comment]
Thanks for your hint, @borisklug. Yea, you are right. Sorry for that :( I don't have much time to work on togglz. But now since @hennr is also part of the team, we will hopefully separate tasks and move things forward.

**Comment by hennr** [comment]
> The last news on https://www.togglz.org/ are still from October 2019. This still confuses new users but also old users like me.
> 
> Maybe just remove the news and all version related stuff on the site and redirect the users to github.
> 
> I also want to say thank you for this great piece of software. At my work - a big insurance company - we use Togglz in an big inhouse application for a lot of things. It works perfect.

I just made the togglz-site pipeline work again, also with some help from @chkal, kudos!
I dropped the news section and will clear the site in general, after that we may need a new tool for the page as awestruct seems unmaintened, see #741

**Comment by hennr** [comment]
Phew, I cleaned togglz.org a lot now.
The "what's new" section points to the github release notes now.
This issue here really had some feature creep, focussing on the whole website not only on the release notes any more.
I guess writing release notes for past releases is not gonna happen, so I tend to close this issue.
@bennetelli and me need to find a good way for release notes for new releases though.

Would be glad if you all could review togglz.org and post issues the corresponding repo https://github.com/togglz/togglz-site/
