### ISSUE TITLE
SonarQube for OSS?

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz#524]

**Comment by hennr** [comment]
https://coveralls.io/ is an option as well.

**Comment by hennr** [comment]
And https://about.codecov.io/
I used the latter on some projects, can't remember why I migrated from coveralls to codecov though :)

**Comment by hennr** [comment]
I set up codecov.
I added a badge to readme and added jacoco for the reports.
They are uploaded for each build now, let's see how this behaves on PRs.

**Comment by bennetelli** [comment]
Then we can close this :)
