### ISSUE TITLE
Don't fail if TogglzFilter is registered more than once

### ISSUE THREAD

**Issue by chkal** [togglz/togglz#53]
There seems to be a bug in Glassfish which causes the TogglzFilter to be executed twice.

https://java.net/jira/browse/GLASSFISH-18548

See report here:

https://groups.google.com/forum/?fromgroups#!topic/togglz-users/vM8alPVUUxM

Perhaps such situations shouldn't result in an exception.

**Comment by jpmsilva** [comment]
Hi @chkal 
You may want to close this one since #291 has been merged :smile:

**Comment by chkal** [comment]
Thanks. Seems like I missed this one. :laughing:
