### ISSUE TITLE
[Question] Can't manage to dynamically pick bean in spring boot

### ISSUE THREAD

**Issue by Venthe** [togglz/togglz#539]
Documentation on site suggests manually defining beans in XML file.
When used with spring boot; bean initialization fails with
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'controller' defined in file [F:\Repositories\_github\Exploratory-Projects\togglz\target\classes\eu\venthe\togglz\Controller.class]: Unexpected exception during bean creation; nested exception is java.lang.IllegalStateException: Could not find the FeatureManager. For web applications please verify that the TogglzFilter starts up correctly. In other deployment scenarios you will typically have to implement a FeatureManagerProvider as described in the 'Advanced Configuration' chapter of the documentation.
```

Is it possible to still use this mechanism in Spring Boot without any additional configuration?

Alternatively; is it feasible for this project to implement Spring events on toggle change? This way I could hook on this event and dynamically set `primary` flag on beans

**Comment by bennetelli** [comment]
Hey, here are some samples of Spring Boot applications without any xml configuration: https://github.com/togglz/togglz-samples
Does this help you with your first question? Please let me know. The examples there don't have any additional configuration.

Regarding the Spring Events.. I actually don't know as I am not that into Spring and your use case at the moment.

**Comment by hennr** [comment]
Nothing heard back so far, closing for now.
Feel free to re-open in case it's still relevant. In best case, provide a demo repo for us **and** check check the examples first:
https://github.com/togglz/togglz-samples
