### ISSUE TITLE
Performant proxy generation using ByteBuddy

### ISSUE THREAD

**Issue by drekbour** [togglz/togglz#572]
Now Togglz baselines Java 8, there are a bunch of performance improvements to had by replacing the Reflection-based JDK proxies from FeatureProxyInvocationHandler with something more custom generated. 

Other libraries exist but my personal preference is ByteBuddy which should be able to do this in a couple of lines. This would need to added as an `<optional>` Maven dependency.
Similarly it doesn't need to change existing Proxy solution, just adds some alternative classes in there.

Happy to PR if all seems acceptable.

**Comment by bennetelli** [comment]
Yes, sure. Would be great :-) Much thanks for all your issues and PRs :-) 

I am also fine with bytebuddy.

**Comment by drekbour** [comment]
Already have this well on the way. Am surprised how much NOT faster it is (~30% faster JDK proxy)

**Comment by bennetelli** [comment]
To be honest I never got in contact with JDK proxies so far. Never touched that piece of code before. So thank you very much for your Issue. I learned something new! that's great :-)

**Comment by drekbour** [comment]
JDK proxy is a little dangerous IMO, primary benefit of new one is not just performance but the fact you can have a _passive_ proxy which is only updated by user code (at a safe-point).

    counterProxy.add(2);
    // (Feature enabled asynchronously)
    counterProxy.add(3);
    // counterProxy = 3 not 5!

As you can see, I've taken interest in togglz :) Will likely PR a few minor things over the next few weeks.

**Comment by bennetelli** [comment]
Thank you very very much :-) happy to have others helping with this project and pushing it forward :)
