### ISSUE TITLE
[Feature]Fetch single toggle endpoint

### ISSUE THREAD

**Issue by mapu77** [togglz/togglz#591]
## Context
As stated in the [documentation of the Spring Boot integration](https://www.togglz.org/documentation/spring-boot-starter.html), by default `togglz-spring-boot-starter` exposes a togglz endpoint as an actuator to list all the toggles from an application. 

This comes really useful in a frontend application to see what toggles are active or not. However, each frontend application has to implement its logic to see if an specific toggle is enabled.

## Improvement
I think it could be really handy to have an endpoint to retrieve the status of a specific toggle to avoid API consumers implement their own logic to know if a feature is enabled or not.
I was thinking of something like `GET `/actuator/togglz/<feature_name>` that returns the `TogglzFeature.java` object itself.

**Comment by klebekj** [comment]
@mapu77 I made this improvement - look at https://github.com/togglz/togglz/pull/634

**Comment by bennetelli** [comment]
thanks for raising that issue and also thanks for opening the PR :)

**Comment by bennetelli** [comment]
merged.
