### ISSUE TITLE
[Feature] Support GCP Cloud Storage as State Repository

### ISSUE THREAD

**Issue by splieth** [togglz/togglz#599]
Hi folks,

I would love to see [Google Cloud Storage](https://cloud.google.com/storage) as a state repository (as a GCP pendant to AWS S3). 
Open for a PR?

**Comment by bennetelli** [comment]
Sure :)

**Comment by bennetelli** [comment]
Right now I am deeply into other things, but I will find some time to support here if needed. 
Feel free to add a PR for it :)
