### ISSUE TITLE
One-click (De)Activation on admin console

### ISSUE THREAD

**Issue by igorrosenberg** [togglz/togglz#60]
See http://www.togglz.org/images/screenshot-admin-console.png

Aim: toggle one feature, stauyin gon main admin page

_v2.0.0 behavior:_
- connect to the admin page, 
- each feature has an edit button, 
- click on one of the edit button, (page redirection, BAD!)
- modify property (via check-box), 
- click on save
- the propery is modified. 

_Desired behavior:_
- connect to the admin page, 
- each feature has a tggle-status-button which says 'deactivate' when the feature is activated, says 'activate' when the feature is de-activated, 
- click on the tggle-status-button, 
- the propery is modifie, without any page redirection.

**Comment by error418** [comment]
Whoops - it seems I forgot to close this issue with my commit message 🙈

**Comment by php-coder** [comment]
@chkal Could you close this issue?

**Comment by chkal** [comment]
Sure! Forgot about this one. Sorry. Thanks @php-coder.
