### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by iherasymenko** [togglz/togglz#607]
Is this an official release? I can't find the release tag nor any mentions about it.

https://repo1.maven.org/maven2/org/togglz/togglz-core/3.0.0/

**Comment by OliverSteenbuck4587** [comment]
+1

**Comment by renatomrcosta1991** [comment]
+1

**Comment by OliverSteenbuck4587** [comment]
Let's see if we can mention @bennetelli to summon him :D

**Comment by bennetelli** [comment]
argh.. sorry.. @iherasymenko and @OliverSteenbuck4587 .. don't have much time to work on it atm.

**Comment by OliverSteenbuck4587** [comment]
No worries, we're simply staying on 2.9.9 until the release shows up on github :)

**Comment by bennetelli** [comment]
it's on GitHub already :) you could also update even when it's not available in the master branch as well as as tag on GH yet as it's already in mvncentral :)

**Comment by OliverSteenbuck4587** [comment]
Cool cool, now I also see the 3.0.0 release commits on GH. Must have missed them earlier. Thanks :)

**Comment by bennetelli** [comment]
you're welcome :) thanks for the hint
