### ISSUE TITLE
How can I push a fix?

### ISSUE THREAD

**Issue by CarlosDong** [togglz/togglz#612]
Hi, I'd like to know how can I create a branch and push a fix? I found that I can't create a branch and push my modified codes upstream.

Thank you.

**Comment by bennetelli** [comment]
Hey, you need to fork the project first (in the top right),then click on the fork button, then checkout your forked project, open a branch and push the changes to the forked repository. After that you should see a notification here which lets you add the PR

**Comment by bennetelli** [comment]
let me know if you need additional help :)

**Comment by hennr** [comment]
@CarlosDong Do you mind to close this issue then?

**Comment by bennetelli** [comment]
I would like to close it as I don't expect to get a response here anymore.
