### ISSUE TITLE
togglz-spring-boot-starter incompatible with Spring Boot 2.6

### ISSUE THREAD

**Issue by mihkelmuur** [togglz/togglz#626]
After update to Spring Boot 2.6 an application relying on `togglz-spring-boot-starter` fails to start:
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-11-23 12:55:09.330 ERROR 17296 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.togglz.spring.boot.actuate.autoconfigure.TogglzManagementContextConfiguration$TogglzConsoleConfiguration.getContextPath(TogglzManagementContextConfiguration.java:62)

The following method did not exist:

    'org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties$Servlet org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties.getServlet()'
...
```

The [Javadoc on `ManagementServerProperties.Servlet.getContextPath()`](https://docs.spring.io/spring-boot/docs/2.5.7/api/org/springframework/boot/actuate/autoconfigure/web/server/ManagementServerProperties.Servlet.html#getContextPath--) suggest to replace `ManagementServerProperties.getServlet().getContextPath()` with `ManagementServerProperties.getBasePath()`:
> _**Deprecated.** since 2.4.0 for removal in 2.6.0 in favor of `ManagementServerProperties.getBasePath()`_

**Comment by hennr** [comment]
I had a look into this and the method together with the corresponding property (to set a prefix path for mangement tooling like actuator etc.) has changed from 2.4.0:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4.0-Configuration-Changelog
key: management.server.servlet.context-path
replacement: management.server.base-path

As pointed out by @mihkelmuur 2.6.0 dropped the old config key suppor and as such the starter breaks.

This calls for a new togglz release which includes this breaking change: Spring-Boot < 2.4.x won't work with this new release.

**Comment by hennr** [comment]
I opened a PR to fix this.
Feedback and reviews are welcome.

**Comment by hennr** [comment]
FYI @PH1P5

**Comment by hennr** [comment]
Thanks for merging, @bennetelli , my pleasure to provide a fix.

I wasn't aware of any sample project until you mentioned them in the PR.
The build seems broken for them though and you may want to build them in github actions now, I guess?

If you need a helping hand there, please let me know.

**Comment by bennetelli** [comment]
> Thanks for merging, @bennetelli , my pleasure to provide a fix.
> 
> I wasn't aware of any sample project until you mentioned them in the PR. The build seems broken for them though and you may want to build them in github actions now, I guess?

Yea, lot of people don't know they exist. I am planning to add them as part of the "normal" projects so we get feedback if it's working for users or not immediately.

> 
> If you need a helping hand there, please let me know.

If you want, you can do it. Otherwise I can do it as well, but this won't happen this week probably.

**Comment by bennetelli** [comment]
> Thanks for merging, @bennetelli , my pleasure to provide a fix.
> 
> I wasn't aware of any sample project until you mentioned them in the PR. The build seems broken for them though and you may want to build them in github actions now, I guess?
> 
> If you need a helping hand there, please let me know.

ah, btw: I will build a new release this evening. So it should be available in Maven central tomorrow morning.

**Comment by hennr** [comment]
All right, great news about the release!
(You may want to include this PR as well ;) It's only maintenance to fix the dependabot version updates: #636)

I will see if I can find some time to work on the github actions part today.

**Comment by bennetelli** [comment]
the new release is there (here and in maven central). I will have to add the release notes, but you can use togglz 3.1.0 with spring boot 2.6 now :)

**Comment by hennr** [comment]
Thanks, I will update our application soon and let you know about how it went :)

**Comment by bennetelli** [comment]
That would be great :)

**Comment by hennr** [comment]
Hi @bennetelli 
It's live and working fine!

Cheers
Henner

**Comment by bennetelli** [comment]
@hennr great :) thx
