### ISSUE TITLE
Unit tests in CDI module don't run

### ISSUE THREAD

**Issue by hennr** [togglz/togglz#658]
As said in #653 I noticed that the unit test for the CDI do not run.
I didn't let the build fail, to get the PR down for the moment (via this https://github.com/togglz/togglz/blob/master/cdi/pom.xml#L21) but this should get fixed nevertheless.

@bennetelli Any ideas why these tests don't run? I could figure it out yet.

**Comment by bennetelli** [comment]
@hennr yes. it's fixed in #669

**Comment by hennr** [comment]
That's great, thanks for the fix!

I just sent another PR to enforce that unit tests are run in the CDI module from now on :)
