### ISSUE TITLE
migrate completely to slf4j, dropping the togglz logging wrapper

### ISSUE THREAD

**Issue by hennr** [togglz/togglz#682]
togglz brings it's own wrapper for logging in the core module.
This will look for slf4j and JUL in the classpath and, if both are there, prefer JUL over slf4j.

Some modules don't use the togglz logging wrapper at all though, namely zookeeper and  dynamodb.

Slf4j is the defacto standard and defaulting to JUL seems outdated to me.
I propose to drop the inhouse logging wrapper (thus the slf4j module, and the SPI stuff around the LogProvider) and migrate all logging to the slf4j api, leaving it to the consumers to provide an implementation like logback during runtime.

I also suggest to using logback for all test logging in combination with a sane logback-test.xml for less verbose, and thus hopefully faster, test runs.

Any opnions on this, @bennetelli ?

**Comment by bennetelli** [comment]
sounds like a good idea. I've never used it my self to be honest.
