### ISSUE TITLE
Improve the process with the 5,000+ Security messages

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz#755]
Lots of them are related to the bootstrap stuff which I personally would not touch.
We could update the bootstrap files once again. It's been a while since we updated these the last time. So this would be good to do again, but I would not try to fix these by editing the files.

If there is no other alternative than removing the security check, this is fine as well. We can still replace it with something else.

**Comment by hennr** [comment]
I would suggest to purge all 5000 issues and start from scratch. I already dropped the CodeQL workflow as 99% of these alerts came from that tool and are related to code style as well. (missing ; at the end of statements etc.)

**Comment by bennetelli** [comment]
That's actually a work for monkeys :-D You can only delete 25 entries and not just all 5.000 entries.

**Comment by hennr** [comment]
aye, it sucks. I wrote a tool to use the gh API. I may can figure something out to use the API to delete them.

**Comment by bennetelli** [comment]
After deleting 200-300 issues, there are actually some issues we could at least take a look at. It's still a pain, but maybe there are some issues worth to take a look at.
