### ISSUE TITLE
Integrations to be removed

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz#786]
* deltaspike
* guice
* zookeeper

**Comment by bennetelli** [comment]
@hennr are you fine with dropping these integrations? I would suggest to drop these integrations and also increase the minimum java version from 8 to 11 and release this as togglz 4.0.0. What do you think?

**Comment by BeLi4L** [comment]
@bennetelli I am migrating an app from Java 8 to Java 17 and I'd love to have the proper GraalVM configuration (done in PR https://github.com/togglz/togglz/pull/600) working with Java 8, do you know if that'd be possible, by any chance? :eyes: Since increasing the minimum version above Java 8 would compromise our migration, unless another solution comes up.

See https://github.com/togglz/togglz/issues/848

**Comment by bennetelli** [comment]
@BeLi4L I could give it a try and try to release the Nashorn replacement first and release the "Java 11 as minimum java version" later.

**Comment by bennetelli** [comment]
It's not. All good :-) and even if it would be, then it would still be worth it :)

**Comment by bennetelli** [comment]
Probably tomorrow after lunch

**Comment by BeLi4L** [comment]
Actually I just tried to upgrade, and everytime I edit a JS script, it gets corrupted and thus, it won't work properly: https://github.com/togglz/togglz/issues/849

**Comment by hennr** [comment]
> @hennr are you fine with dropping these integrations? I would suggest to drop these integrations and also increase the minimum java version from 8 to 11 and release this as togglz 4.0.0. What do you think?

No veto from my side here!

**Comment by bennetelli** [comment]
Looks like there are actually still people using zookeeper: https://stackoverflow.com/questions/72710485/zookeeper-znode-connection-limit 

we should keep that stuff

**Comment by bennetelli** [comment]
@BeLi4L i hope the current release is fine for you?

**Comment by BeLi4L** [comment]
@bennetelli Yes it looks fine, thank you :blush:

**Comment by hantsy** [comment]
Java 17 is ok, and Spring 6/Spring Boot 3 requires Java 17.

**Comment by bennetelli** [comment]
yep. We have to use Java 17 as minimum.
