### ISSUE TITLE
3.2.1 release changelog

### ISSUE THREAD

**Issue by tiagojufr** [togglz/togglz#815]
I noticed https://mvnrepository.com/artifact/org.togglz/togglz-console/3.2.1 is available but I don't see the release here on github.
Is there any place I can see the changelog for that release?

**Comment by hennr** [comment]
Hi there,

the automated process is still in the making, true.
I am not able to work on it ATM though, sorry.
To your initial question: no, there is no release log for 3.2.1 :/
