### ISSUE TITLE
GraalVM misconfiguration

### ISSUE THREAD

**Issue by BeLi4L** [togglz/togglz#848]
I am migrating an app from Java 8 to Java 17. I updated the JS engine it uses from Nashorn to GraalVM JS.

The **problem** is: the `ScriptEngine` instance retrieved by Togglz in `ScriptEngineActivationStrategy.java` is not configured properly, and Java methods aren't accessible inside the JS engine (e.g. `user.getAttribute()`), which makes the whole migration complicated.

Do you know if there's a way around that?

Or I should wait until https://github.com/togglz/togglz/pull/600 is released? :thinking: 

_Example error:_

```
GRAVE: Could not evaluate script for feature MY_FEATURE: org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (getAttribute) on org.togglz.core.user.SimpleFeatureUser@5e3c72d1 failed due to: Unknown identifier: getAttribute
```

**Comment by bennetelli** [comment]
hey @BeLi4L I had the same issue if I remember correctly. 

I think it should also work for you if you would wait for #600 to be released. Is that something that would work for you? 

If I got you correctly then you are using an already released version of togglz which does not contain #600? If yes, then it won't work when you add the Graal VM JS dependencies to your application pom.xml/build.gradle while togglz still uses Nashorn.

**Comment by BeLi4L** [comment]
Thank you for your quick answer :wink: 

Actually, somehow, as soon as I added the `graalvm` dependencies in my pom.xml, Togglz started using the GraalVM engine automatically. I guess the ScriptEnginerFactory provided the recommended engine registered for "ECMAScript" (or "js" or whatever)? :shrug: 

And yes, if https://github.com/togglz/togglz/pull/600 is released, it should fix my problem :relaxed:

**Comment by bennetelli** [comment]
Unfortunately I can't release a new version today because of a new notebook without credentials. 
Need to set up that stuff again first. Would it also be okay for you to get the release next week, @BeLi4L ?

**Comment by BeLi4L** [comment]
Yeah sure, I need to fix the issue with the [JS script encoding issue](https://github.com/togglz/togglz/issues/849) first anyway ;)

**Comment by BeLi4L** [comment]
Fixed! :partying_face: 

Now I am ready for a new release, when you're ready :wink:

**Comment by BeLi4L** [comment]
@bennetelli Do you have an idea of when the next version will be released?

I'm considering using a fork, temporarily, but if the new release is coming soon, then it won't be necessary :yum:

**Comment by bennetelli** [comment]
hey @BeLi4L sorry for my late response. I will give it a new try today at 5pm and will give you feedback here

**Comment by bennetelli** [comment]
I guess this issue can be closed. Please ping me if I am wrong.
