### ISSUE TITLE
JavaScripting API: encoding issue

### ISSUE THREAD

**Issue by BeLi4L** [togglz/togglz#849]
## Context:

I upgraded from Togglz version 2.8.0 to 3.2.1, but can't edit JavaScript scripts anymore, since every special character gets encoded.

E.g. `'` becomes `&#39;`, `<` becomes `&lt;`, etc. 

## What I did:

![image](https://user-images.githubusercontent.com/8281983/193040895-579f4dd8-51bd-4de6-bffc-877b9062f6f0.png)

## Actual result:

![2022-09-29_15-04](https://user-images.githubusercontent.com/8281983/193040172-43a4576b-4f60-4e4a-8f82-8a9c68b30f86.png)

# Expected result:

![2022-09-29_15-11](https://user-images.githubusercontent.com/8281983/193040472-c74f30ac-77d8-4f93-9b47-e8208b877a37.png)

# Explanation

This may have been introduced by https://github.com/togglz/togglz/pull/449/files#diff-7f7c17da3ef3b2dd9fba8c230694bfcfae96fa0e6d98c376730ed5c73484bc64R61. This prevents me from upgrading at all :sweat_smile: 

I'm not familiar with the Togglz codebase, but what was the XSS bug that MR tried to fix exactly? :thinking:

**Comment by bennetelli** [comment]
Argh.. as far as I remember correctly I just copied the changes from @JoeBeeton. Maybe he can tell us more about it?

**Comment by BeLi4L** [comment]
Here is a PR that should fix this bug (I hope?): https://github.com/togglz/togglz/pull/856

I also rolled back the "Mandatory Java 11" changes if that's OK :yum:

**Comment by BeLi4L** [comment]
@bennetelli Thank you for merging my PR :wink: 

By any chance, do you already have an estimate of when the next release is gonna occur?

**Comment by BeLi4L** [comment]
Wait, actually I think my PR doesn't solve the core issue. It is properly displayed in the console UI, but not stored properly in DB, so the JS is not executed properly.

I should sanitize the input, not escape it entirely. I'll do another PR :wink:

**Comment by BeLi4L** [comment]
Fixed in https://github.com/togglz/togglz/pull/858
