### ISSUE TITLE
Release 3.3.0

### ISSUE THREAD

**Issue by bennetelli** [togglz/togglz#864]
Hey @hennr, unfortunately I can't release a version at the moment. Can you release 3.3.0 maybe and get in touch with me afterwards? 
This would be great :-) 

cc: @BeLi4L

**Comment by hennr** [comment]
Hi @bennetelli,
I fixed two problems but it seems that you dropped the needed maven profile (central-deploy) just the commit after I added it; see 18f96f0e7f3eae1c8c79af7a3105fc605bdc670e
We would need to add it again, not sure when I will have time either though. Sorry.

**Comment by hennr** [comment]
I added the profile back in today, but now the samples project seems to block the release process.
Could you have a look on how to ignore the samples module for releases, @bennetelli ?

**Comment by hennr** [comment]
Finally there @BeLi4L, see https://github.com/togglz/togglz/actions/runs/3463279405/jobs/5783286332

@bennetelli , could you have a look on the released artifacts and check if something got released which should not be there?
I excluded the samples for example. Is there anything else?
If you, you could remove it from the list here:
https://github.com/togglz/togglz/blob/master/.github/workflows/maven-central-release.yml#L33

**Comment by bennetelli** [comment]
Good to have you in the team. Thank you  very much @hennr :) I did not have time to work on it.

I think that should be it. But I will take a look at an older release and compare the artifacts.

**Comment by bennetelli** [comment]
I am wondering if we should expect to see an togglz-project artifact in 3.3.0 here: https://search.maven.org/search?q=org.togglz ?
And right now it's on maven central, but not distributed on mvnrepository for example: https://mvnrepository.com/artifact/org.togglz/togglz-core

**Comment by hennr** [comment]
Well, yes, togglz-project shoudl be there!

**Comment by hennr** [comment]
I added a tag 3.3.1 and built a new release 3.3.1 which should be favoured now.


Regarding mvnrepository: it's outdated per default in my experience and should not be used.

**Comment by bennetelli** [comment]
Much thanks :)

**Comment by BeLi4L** [comment]
Wait, mvnrepository is outdated? :scream:

**Comment by hennr** [comment]
I didn't say it's deprecated, I said it's often outdated.

This is my personal experience.
