### ISSUE TITLE
Feature isActive fails when run inside Java parallelStream

### ISSUE THREAD

**Issue by ravindarreddy1** [togglz/togglz#865]
Get the following error when the Enum Feature method isActive() is called inside a Java parallelStream. Please advice:

Sample code:

        public enum TogglzFeatures implements Feature {
	        @Label("Test Togglz Configuration Feature")
	        TEST_FEATURE_TOGGLZ
        }

	public void someMethod() {
		Arrays.asList(1, 2, 3).parallelStream().forEach(i -> {
			try {
                                 //Below call fails on some iterations but consistently!
				TogglzFeatures.TEST_FEATURE_TOGGLZ.isActive();
			} catch (Exception e) {
				System.out.println(e.getMessage());
			}
		});
	}

	@GetMapping
	public Void getSomething {
		someMethod(); 
	}

**Error Message:**
java.lang.IllegalStateException: java.lang.IllegalStateException: `Could not find the FeatureManager`. For web applications please verify that the TogglzFilter starts up correctly. In other deployment scenarios you will typically have to implement a FeatureManagerProvider as described in the 'Advanced Configuration' chapter of the documentation.

**Comment by ptriller** [comment]
You would have to pass the FeatureManager Manually
```
    public enum TogglzFeatures implements Feature {
        @Label("Test Togglz Configuration Feature")
        TEST_FEATURE_TOGGLZ
    }

public void someMethod() {
        FeatureManager featureManager = FeatureContext.getFeatureManager();
	Arrays.asList(1, 2, 3).parallelStream().forEach(i -> {
		try {
			featureManager.isActive(TogglzFeatures.TEST_FEATURE_TOGGLZ);
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
	});
}

@GetMapping
public Void getSomething {
	someMethod(); 
}
```

Other than that, the code if the `ThreadLocalFeatureManagerProvider` in Togglz would have to change to use `InheritableThreadLocal` instead of `ThreadLocal` but I  have no idea if that would have unintentional side effects.

**Comment by bennetelli** [comment]
@ravindarreddy1 your solution is up there. Will close that issue.
