### ISSUE TITLE
Move away from spring.factories for auto-configurations for Integration

### ISSUE THREAD

**Issue by rajadilipkolli** [togglz/togglz#878]
The way beans are autoconfigured is changed in [spring boot 3](https://github.com/spring-projects/spring-boot/issues/29872), This was introduced in spring boot 2.7.x. As a result, unable to with togglz version 3.2.1 unable to use it.

Documentation [here](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#features.developing-auto-configuration.understanding-auto-configured-beans)

**Comment by bennetelli** [comment]
already part of the current master state.
