### ISSUE TITLE
togglz uses SLF4J 2.x and logback 1.2.x which do not play together.

### ISSUE THREAD

**Issue by ptriller** [togglz/togglz#879]
In the root pom.xml slf4j was updated to version 2.0.3 but logback is still 1.2.10

slf4j dropped compatibility by some degree:
https://logback.qos.ch/download.html

There you can see that 1.2.x is for slf4j 1.7.x and 1.4.x is for slf4j 2.x

slf4j is binary backward compatible for clients but the logging bindings are not binary compatible.

https://www.slf4j.org/faq.html

**Comment by ptriller** [comment]
Spring boot 3.0 is on slf4j 2 and the 2.x series is on 1.7

**Comment by bennetelli** [comment]
Maybe I need coffee.. but: doesn't that mean we can't support java 8 and java 11 at the same time?

**Comment by ptriller** [comment]
It's not that bad. 
The only dependency for logback in togglz is for testing as far as I could see.
And until the complete switch is done slf4j-1.7 could be used in togglz for compiling. Applications that include togglz could use slf4j 2 without any problem , because the APIs are backward compatible. 
If slf4j2 is used in togglz and nobody uses the new API in togglz, then I think it also would work.
It would however break if togglz includes slf4j2 and uses parts of the new API, then of course backward compatibility is lost.

The only place where there is no backward compatibility for slf4j2->slf4j1 is when you choose implementations for logging, so logback or similar frameworkds. there the version must match.

At least that is how I understood the documentation for slf4j/logback, I did not do any extended testing.

**Comment by hennr** [comment]
Thanks for brining this up @ptriller.

You are right, togglz uses logback for test logging only, we only bring a dependency to slf4j for the users.

We should upgrade to logback 1.3.4 then and wait with the upgrade to 1.4 until we drop java 8 support.
I also added a comment in #863

**Comment by hennr** [comment]
We are now on logback 1.3.4 (for internal test logging) and slf4j 2.x (see #890)
This issue is closed then, right @ptriller ?

**Comment by ptriller** [comment]
Yes @hennr, that should fix the incompatibility issue

**Comment by hennr** [comment]
Thanks for the fast reply. Closing as fixed then, should be done with the next release, see #864 for that.
