### ISSUE TITLE
slf4j version differs from spring-boot complicating the usage of togglz

### ISSUE THREAD

**Issue by hennr** [togglz/togglz#904]
As noted by @napstr in #859 togglz uses slf4j v2 now is is not compatible with spring-boot 2.x which relies on slf4j v1

I suggest to rollback to slf4j v1 in togglz and wait for spring-boot to upgrade to slf4j as well.

**Comment by hennr** [comment]
I just send a PR and we should have a new release afterwards.
What do you say @bennetelli , @napstr ?

**Comment by bennetelli** [comment]
i am fine with it

**Comment by hennr** [comment]
All right, let's have it this way then.
I will build a new release now.

**Comment by hennr** [comment]
3.3.2 is out.
