### ISSUE TITLE
Console as standalone .war

### ISSUE THREAD

**Issue by mattcorey** [togglz/togglz#91]
A pre-build .war file supporting minimal configuration would be massively useful for systems with multiple applications depending on a single Togglz configuration data store.  Ideally, it would be accompanied with Chef or Puppet configured box(es), as well as a Vagrant file.

**Comment by bennetelli** [comment]
Anyone still interested in it? I think its more or less obsolete in times of fat jars with Spring Boot, Quarkus and so on.
