### ISSUE TITLE
Samples version outdated

### ISSUE THREAD

**Issue by PB-TW** [togglz/togglz#921]
I tried to run the samples but they failed because certain resources did not exist for version 3.2.1-SNAPSHOT.
Changing the version in these lines to 3.3.3 made it work.

https://github.com/togglz/togglz/blob/b05f204d9f31613d95655f0e0a43f833802b0747/samples/pom.xml#L11
https://github.com/togglz/togglz/blob/b05f204d9f31613d95655f0e0a43f833802b0747/samples/pom.xml#L21

**Comment by bennetelli** [comment]
Thanks. You are right. Looks like we need to change our release process again.

**Comment by bennetelli** [comment]
Seems to be fixed by the release process already. Thanks for raising this issue. I will clsoe it and keep an eye on it during the next milestone releases of togglz 4
