### ISSUE TITLE
Deleting outdated feature flags

### ISSUE THREAD

**Issue by MohamedAymanN** [togglz/togglz#944]
I cannot find a way to delete outdated feature flags using a JDBCStateRepository, is this supported in anyway?

**Comment by bennetelli** [comment]
What do you mean with outdated? 

Usually the workflow is like this:
* add a new feature
* surround it with the typical if(Feature .. .isActive()) { ... } else { // the old stuff }
* then you push your new feature
* turn it on on your environment and test it
* if it's working as epected -> change the code and remove the else block as well as the surrounding if (Feature.. isActive() so your new Feature becomes the new default.

I am wondering how a feature could become outdated in your workflow?

**Comment by MohamedAymanN** [comment]
Hey @bennetelli ,


Maybe I was not that clear. I meant when the feature flag is outdated. As you said in the last step to remove the if condition with the feature flag. Using the JDBCStateRepository or maybe other cases as well. The entry is left stale in the Database without being deleted. We had to delete these entries manually.

**Comment by bennetelli** [comment]
Yes, I would say this is the normal way to go. Most of the time I am using either S3 buckets or GCP Cloud Buckets to store the Feature state and there I have to delete the state manually when removing the surrounding if else block as described above.

What do you have in mind to delete this non-manually? The only thing that comes to my mind is: deleting the state when someone disables the toggle. I am open for suggestions :)

**Comment by MohamedAymanN** [comment]
That could be an option. Additionally, just adding a function in the StateRepository to be able to do that, similar to how we fetch the features. So to have everything through one interface.

**Comment by bennetelli** [comment]
Then someone still has to call that function.

So in case I added a if(Features.XYZ.isActive() { //... }, this feature is working and I now want to delete the surrounding block again and make it the default case, then I still would have to call the method from somewhere to delete the stuff in the repository. Right now I don't see the benefit in adding a method which would have to be called from someone :/ I mean, deleting the single feature status in the repository is pretty straightforward, isn't it?
