### ISSUE TITLE
Error to start tomcat with spring boot 3.0.2 /togglZ 4.0.0M1

### ISSUE THREAD

**Issue by ZodZekri** [togglz/togglz#945]
Hello team , 
I have this issue when i update togglz to this version 4.0.0M1 and spring boot 3.0.2 
: Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'org.togglz.spring.boot.actuate.autoconfigure.TogglzAutoConfiguration$TogglzConsoleConfiguration': Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'togglz-org.togglz.spring.boot.actuate.autoconfigure.TogglzProperties': Could not bind properties to 'TogglzProperties' : prefix=togglz, ignoreInvalidFields=false, ignoreUnknownFields=true :{}
Can someone Help please i try to see the config in togglzproprites to see some validator but i put every config and i have the same error. this my config 

togglz:
    enabled: true
    console:
        enabled: true
        path: /admin/togglz-console
        secured: true

**Comment by bennetelli** [comment]
Hey @ZodZekri,

right now togglz 4 is a milestone and not a final release yet. I will have some time to work on it next week.

In the meantime you could use togglz 3.3.3 with Spring boot 2. this is still working

**Comment by hantsy** [comment]
The autoconfiguration classes of togglze 3.3.3 are not scanned in Spring Boot 3(changes the registrations), but after importing it manually, worked.

**Comment by bennetelli** [comment]
thanks for your hint, @hantsy :) I am currently working on it and will release a fix until friday

**Comment by bennetelli** [comment]
adding this line to your spring boot application class makes it working as expected again:

@Import({TogglzAutoConfiguration.class, TogglzEndpointAutoConfiguration.class})

I am working on it and will release a new version which makes adding these explicitly obsolete so togglz behaves as it did so far

**Comment by hantsy** [comment]
@bennetelli The autoconfiguration classes registration in `spring.factories` does not work since 3.0, use `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` instead.

See:  https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files and https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration

**Comment by bennetelli** [comment]
> @bennetelli The autoconfiguration classes registration in `spring.factories` does not work since 3.0, use `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` instead.
> 
> See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files and https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration

with the latest milestones of togglz 4.0.0-M1 this is working as expected. So this issue will disappear when togglz 4.0.0 comes out.

**Comment by bennetelli** [comment]
I tested it with the latest milestone release 4.0.0-M4 and it's working.
