### ISSUE TITLE
Make GraalVM JS dependencies optional

### ISSUE THREAD

**Issue by dreis2211** [togglz/togglz#952]
Hi,

I've noticed that since 3.3.0 our fat JAR sizes exploded. A little bit of investigation shows that #582 introduced dependencies on `org.graalvm.js`. This is almost ~50MB large in 22.0.0 (the version used in 3.3.3). While newer version are only 22MB large, these dependencies should be optional.

I guess most users don't even use the `ScriptEngineActivationStrategy` that depends on  `org.graalvm.js`.

We could workaround this by manually excluding the dependency, but I'd rather get rid of this in the long run.

Cheers,
Christoph

**Comment by bennetelli** [comment]
Hey Christoph,

thanks for your issue. With "manually excluding" you probably mean exclude the dependency in your pom.xml or build.gradle? 
This would solve your issue, but is somehow not that nice from a users perspective. At least when someone starts to use the activation strategy, then you should get in trouble at runtime I guess.
Need to think about it once again. Separating this dependency from the others by introducing a new module is a bit of oan overkill in my opinion. Do you have something else in mind maybe?

best regards
Bennet

**Comment by bennetelli** [comment]
just added a ticket for it. see #958 

will think about it

**Comment by dreis2211** [comment]
@bennetelli Again - I don't think this is necessary....Just specifying the two graalvm JS dependencies as optional should probably suffice, shouldn't it? E.g.
```patch
--- a/core/pom.xml
+++ b/core/pom.xml
@@ -35,11 +35,13 @@
       <groupId>org.graalvm.js</groupId>
       <artifactId>js</artifactId>
       <version>22.0.0</version>
+      <optional>true</optional>
     </dependency>
     <dependency>
       <groupId>org.graalvm.js</groupId>
       <artifactId>js-scriptengine</artifactId>
       <version>22.0.0</version>
+      <optional>true</optional>
     </dependency>
```
I mean of course this would require a bit of documentation that you need to include these two dependencies on your own, but I guess the majority of users doesn't use the respective activation strategy in the first place (might be a wrong assumption.)

**Comment by bennetelli** [comment]
added a PR here: #964. Thanks for the hint :)

**Comment by bennetelli** [comment]
Even moving the activation strategies to its own module wouldn't solve this issue.. so I would have to create a separate module for this activation strategy to avoid this blown up jar size.. which is isn't that nice.. so this seems to be the best solution for it.
