### ISSUE TITLE
Create or Add & Delete new toggle capability on togglz console web page

### ISSUE THREAD

**Issue by satishjs2297** [togglz/togglz#965]
Currently togglz console web  GUI should have add toggle capability to add or delete the toggles. This helps to enable activate the configurable togglz interface to consume the toggles from the respective application.

**Comment by bennetelli** [comment]
i don't really get your usecase. 

Usually the developer adds feature toggles in the code. So the code is the single point of truth. 
Adding a delete and add button to the UI would lead to a weird behavior when adding a toggle which is not part of the code yet.

What is your approach in that case? What do you expect to happen when someone adds or removes a toggle in the UI and the code either does not contain or contain the toggle?
