### ISSUE TITLE
Integration with Thymeleaf

### ISSUE THREAD

**Issue by php-coder** [togglz/togglz#98]
There is already a repo with Togglz & Themeleaf integration: https://github.com/heneke/thymeleaf-extras-togglz But this artifact isn't published in maven repository and looks orphaned. Probably, you can add such integration by yourself or pull existing ones?

**Comment by bennetelli** [comment]
Had a chat with the maintainer of thymeleaf-extras recently and we decided to integrate the source code in togglz itself so we don't need to build two releases dependend of each other. 
Users will get the same behaviour as before by using the togglz-spring-boot-legacy-starter and togglz-spring-boot-starter
