### ISSUE TITLE
Mention on the site about slf4j, mongodb and guice integration

### ISSUE THREAD

**Issue by php-coder** [togglz/togglz#99]
I've read the site and didn't found any mentions about modules for slf4j, mongodb and guice integrations. It would be useful for newcomers to know about these features.

**Comment by guidosteinacker1969** [comment]
@bennetelli, is this something that you could fix when polishing the Togglz site?

**Comment by bennetelli** [comment]
@guidosteinacker1969 sure. Will fix it.

**Comment by hennr** [comment]
Some modules don't exist anymore.
We need a new ticket for the site overhauling anyways.
