### ISSUE TITLE
Is there anyway to extend or customized Admin console UI

### ISSUE THREAD

**Issue by kumudgarg** [togglz/togglz#990]
If anyone know above query, please let me know.

**Comment by kumudgarg** [comment]
Okay. Can i add the column like clients, or organisation name. As we have
seen like features, actions, status. Like that i want to add another column
over ui.

**Comment by bennetelli** [comment]
no, you can't. I've never had a use case like that before. Sorry :/ Right now you can't do that with the UI

**Comment by kevinstembridge** [comment]
I think what Kumud wants to do can be achieved with custom @FeatureAttribute annotations. Although, the information wouldn't be displayed in columns. 

See my response on StackOverflow.
https://stackoverflow.com/questions/75916796/is-there-any-way-to-customized-or-extend-admin-console-ui/76140458#76140458

**Comment by bennetelli** [comment]
maybe I did not understand you correctly. Does this solve your issue, @kumudgarg ?

**Comment by bennetelli** [comment]
closed as I did not get a response.
