### ISSUE TITLE
Jakarta 9.1 support (Servlet 5.0 instead of 6.0)

### ISSUE THREAD

**Issue by vincent-nagy** [togglz/togglz#991]
Currently the 4.0.0-M4 version of Togglz only supports jakarta 10 through the use of servlet 6.0. It would be nice to also support Jakarta 9.1 which makes use of servlet 5.0.

This currently raises the following exception when used in combination with openliberty:
[INFO] [INFO    ] FFDC1015I: An FFDC Incident has been created: "com.ibm.wsspi.adaptable.module.UnableToAdaptException: com.ibm.ws.javaee.ddmodel.DDParser$ParseException: CWWKC2263E: The webapp : WEB-INF/lib/togglz-servlet-4.0.0-M4.
jar : META-INF/web-fragment.xml deployment descriptor on line 4 specifies version 60, which is higher than the current provisioned version 50. com.ibm.ws.webcontainer.osgi.WebContainer createModuleMetaData" at ffdc_23.04.03_11.52.28
.0.log

**Comment by hantsy** [comment]
Spring test mockmvc requires Servlet 6.0.

**Comment by bennetelli** [comment]
I will try to find a way to support both.

**Comment by bennetelli** [comment]
@vincent-nagy can't u just update your openliberty version? It seems that OpenLiberty is supporting Jakarta 10: https://openliberty.io/start/

**Comment by bennetelli** [comment]
hey @vincent-nagy ping :)

**Comment by vincent-nagy** [comment]
Hi

Sorry for the delayed response. We went straigth to jakarta 10 because of this issue. I understand the predicament you're in supporting jakarta 9, nevertheless I do still feel a library as popular as togglz shouldn't skip major versions of frameworks like jakarta.

While this is no longer an issue to me and my team, there are a lot of big companies and government organizations who rely on jakarta and prefer to migrate version by version instead of skipping over jakarta 9.
